### ISSUE TITLE
survey.clear doesn't clear added dynamic panels/rows

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1083]
### Are you requesting a feature, reporting a bug or ask a question?

bug maybe

### What is the current behavior?

when I try to clear survey with panel/matrix dynamic elements panels and rows data are cleared but they keep shown (empty) in the survey

### What is the expected behavior?

I'd like to undo all survey changes by pressing clear button

### How would you reproduce the current behavior (if this is a bug)?

http://plnkr.co/edit/L8BfYQ?p=preview (add some row/panels with data and then press clear)

**Comment by andrewtelnov** [comment]
@masciugo  Yes, it is a bug. I am not sure how to fix it yet. Likely we will need to save the initial rowCount and panelCount and set them on clear method.
Anyway the behavior is not expected and it is definately a bug.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
Hello. We have tried to find a quick solution. But unsuccessfully for now. Because we didn't find a complete solution for all possibler scenarios - assigning default values, just reset data, etc. We'd like to propose a workaround for you - http://plnkr.co/edit/3LwcbN?p=preview
Please let us know whether it is a suitable approach for you.

**Comment by masciugo** [comment]
yeah that's exactly the workaround I adopted while was waiting for a solution :) Thank you
