### ISSUE TITLE
inplaceEditForValues allows users to save empty values.

### ISSUE THREAD

**Issue by wagnermaciel** [surveyjs/survey-library#1667]
[Link to an example plunker](https://embed.plnkr.co/XxDE0BRFlqvL4zzxnHfs/)
[Link to video of how to reproduce this bug using the above plunker](https://drive.google.com/file/d/17eliKY9_zVhRYaG4OadjV_Bf5UbL0qN1/view?usp=sharing)

### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
When inplaceEditForValues is set to true, users are able to save an empty value by editing in place.

### What is the expected behavior?
The same behavior as when inplaceEditForValues is false.

### How would you reproduce the current behavior (if this is a bug)?
1. Go to the example linked above, or create a survey where creatorOptions has inplaceEditForValues set to true.
2. Create a dropdown.
3. In place edit an option to have to be empty.
4. Go to Test Survey.
5. Expand the dropdown.
6. Observe that the option is displayed as [object Object] as a result of this issue.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://embed.plnkr.co/XxDE0BRFlqvL4zzxnHfs/

Test code

**index.js**
```
var creatorOptions = {
  inplaceEditForValues: true
};
var creator = new SurveyCreator.SurveyCreator("creatorElement", creatorOptions);
```

### Specify your

* browser: Google Chrome
* browser version: 73.0.3683.103
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.0.83

**Comment by andrewtelnov** [comment]
@wagnermaciel It is definitely a bug. We probably should restore the previous value when a user tried to enter an empty value.
What do you think?

Thank you,
Andrew

**Comment by wagnermaciel** [comment]
@andrewtelnov Thanks for getting back to me so quickly! I agree, as this is the way it works when inplaceEditForValues is left undefined.

When do you think this issue could be resolved by (asking for my team lead)?

Best,
Wagner Maciel

**Comment by andrewtelnov** [comment]
@wagnermaciel I have fixed the issue. However, I have fixed it on the SurveyJS Library level. The issue was in incorrect deserialization of JSON object.
The following JSON is deserialized incorrectly:
```
    {
     "type": "dropdown",
     "name": "question1",
     "choices": [
      {},
      "item2",
      "item3"
     ]
    }
```
item.value equals to {} (empty object), instead of null.

I have added [a new Unit Test](https://github.com/surveyjs/survey-library/commit/1b9fb1901616fdfea6b959a9fa85521325aac9a2#diff-af211a715b8cd78ffd7293c6b81f90ccR671).

The SurveyJS Creator user may enter an empty item value. I think we will leave this ability of now.

We are releasing new minor version with bug fixes and new functionality every week, commonly on Tuesday. If you need the fix faster, then you may build the library by youself, please follow instructions in readme file of this repo.

Thank you,
Andrew
