### ISSUE TITLE
sharing data between checkbox and panel dynamic questions 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1741]
### Are you requesting a feature, reporting a bug or asking a question?

bug (maybe)

### What is the current behavior?

I am trying to slightly modify the following example
https://surveyjs.io/Examples/Library/?id=survey-shareddata&platform=jQuery&theme=default

I want to simplify the first question about employers using a simpler checkbox question

https://plnkr.co/edit/KR1hYmGCt4BOFkibfAdV?p=preview

### What is the expected behavior?

I'd like to use the first question answer in the second question but it seems that the answer must be an array of objects and not an array of string. Why?

**Comment by masciugo** [comment]
plunker added in description

**Comment by tsv2013** [comment]
The mentioned example shows how to share data between matrix dynamic and panel dynamic questions. This is possible due to both questions have the same storage format - an array of objects.

Your case has incompatible questions storage format - an array of strings (checkbox) vs an array of objects (paneldynamic). That's why it shouldn't work.
