### ISSUE TITLE
populate fields exploiting dropdown based on an external service

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1821]
### Are you requesting a feature, reporting a bug or asking a question?

question

I am looking for a way to populate fields with data depending on the current selection of an other dropdown question which is based on an external service. For example in [this plunk](https://plnkr.co/edit/QqQounI9kr5okZdI0nWh?p=preview) I'd like to populate capital field automatically after selecting the country

Is there any native way to do it? I think that could be really useful in general, not only in my case

thanks

**Comment by andrewtelnov** [comment]
@masciugo We have introduced the async expression recently. You may use them. Here is [the example](https://surveyjs.io/Examples/Library/?id=questiontype-expression-async).

Thank you,
Andrew

**Comment by masciugo** [comment]
ok very powerful technic that I'll use more for expression that depends on remote data their self. 

In both examples we mentioned I would expect instead something lighter: a way to connect value of two questions in a more articulated way. If behind the value of the question1 there is an object (like for example the returned JSON of a remote service) I imagine a way to reach that object from other questions choosing then a different property so that you will not need to make another remote call to fetch that object using the param coming from the first question

that's just an abstracted idea

thank you

**Comment by andrewtelnov** [comment]
@masciugo In this example we are doing this. We are fetching the information about the country and store it in the hash object: countriesInformation, countriesInformation["countryName"] will return you the object about the country if it is fetched or tell your that you have to wait, since we have already sent the request, but have not got the result from the server yet, or there is an error, the country with the requested name doesn't exists.
Probably the code is not that light, and there is the isReadyCallbackList array, that nodify all async functions that the requested information about the country has been returned.
However, I have to say, that async world is not as simple as sync. To do it right, you have to write some code.
We have written a lot of code to make sure that async expression validation works correctly.
The end-user press the "Next" button, but the survey doesn't go to the next page is there is an async validation. It should wait till all async validation passed and based on results go to next page or show an error(s).

Thank you,
Andrew

**Comment by masciugo** [comment]
fair enough. Thank you for taking time to explain

**Comment by masciugo** [comment]
[Here](https://github.com/surveyjs/survey-library/issues/1935) an acceptable solution, based on @andrewtelnov suggestion

However, while working on that issue, I realised that my initial idea was not that bad because reduce a lot the number of async calls consistently with your statement

> However, I have to say, that async world is not as simple as sync. To do it right, you have to write some code.

Let me reword it:

when using choicesByUrl an array of objects si fetched. When you select your option in the dropdown one of those object is chosen but only a one/two properties of it are _stored_ someway in the question (value and title). If it would be possible to store in the question the whole object (in a _sourceValueObject_ property) and let it accessible by other expression questions in a way like `{questionName.sourceValueObject.sourceValueObjectProperty}` or assign part of it directly to the _survey.data_ programmatically changing whole branches of the survey data all in once without doing any other async call

On the other hand, maybe, this would have many implications for the core code that I cannot see or an overuse of it may generate significant side effects
