### ISSUE TITLE
"clearInvisibleValues": "onHidden" not working with preloaded data and nested dynamic panels

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1866]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

survey does not get filled with all preloaded data when using `"clearInvisibleValues": "onHidden"`

### What is the expected behavior?

it should

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/okawWEwty6DCRdFozb5r?p=preview

comment out `"clearInvisibleValues": "onHidden"` to have it working

**Comment by masciugo** [comment]
version 1.0.91 works

**Comment by andrewtelnov** [comment]
@masciugo I have added a unit test and fixed it. It did work in v1.0.91 indeed. However, I could not understand how it might work. 
The issue happens when "clearInvisibleValues": "onHidden", set data to survey.data and for nested/child dynamic panel (dynamic panel in dynamic panel).
Anyway the fix is added and we will include it into next minor update v1.1.17

Thank you,
Andrew

Thank you,
Andrew
