### ISSUE TITLE
onClearFiles callback wrongly called

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1966]
### Are you requesting a feature, reporting a bug or asking a question?

bug maybe

### What is the current behavior?

if I add a callback onClearFiles event it is called as soon as I try to upload a file (I don't know why) and, above all, prevent onUploadFiles event from being triggered. If I simply remove onClearFiles callback onUploadFiles event is correctly triggered

### What is the expected behavior?

onClearFiles event should not be triggered while uploading

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/zA1A28f8jacyxSee6pv6?p=preview

**Comment by tsv2013** [comment]
If file question wasn't empty, it will be overriden via selected file. In this case (you are storing files on a server) you probably will want to remove file from a server - and this can be achieved on the `onClearFiles` event.

Since `onClearFiles` is async, the `onUploadFiles` only after successful clear (if clear handler exists)
