### ISSUE TITLE
If page has visibleIf but visible: false, page is still visible according to visibleIf

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#2020]
### Reporting a bug
Page's visibleIf trumps visible setting.

### What is the current behavior?
If page has visibleIf but visible: false, page is still visible according to visibleIf.

### What is the expected behavior?
If page has visibleIf but visible: false, page should not be visible.

### How would you reproduce the current behavior (if this is a bug)?
Add a visibleIf to a page. In my case I check if a checkbox question on the first page is not equal to a certain value. This visibleIf is set on page 3 and 4 of my survey.
In my backend I set the visible setting to false in the case where I only want to show the first page of my survey, but page 3 and 4 are still shown according to the visibleIf.

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.5.13

**Comment by andrewtelnov** [comment]
@Lionqueen94 This is the expected behavior.
Here is the doc for [visibleIf property](https://surveyjs.io/Documentation/Library?id=questiontextmodel#visibleIf). We likely need to add a text that visibileIf overrides visible property.
What is your scenario? I am pretty sure, that you can achieve what you need by using visibleIf expression and, for example, survey.caclulatedValues. like:
``visibleIf = "{The current Expression} and {mycalculatedValue} = 'visible'"``, where mycalculatedValue is 'invisible' initially.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Ah thanks for the quick response! I have now fixed it by removing visibleIf properties on pages in the case when I only want to show the first page. That is working fine now so since it's the intended behaviour I'll keep this line in my code.
