### ISSUE TITLE
Support validating external captcha

### ISSUE THREAD

**Issue by cdalexndr** [surveyjs/survey-library#2041]
### Are you requesting a feature, reporting a bug or asking a question?
question

I'm trying to use an external captcha for validation. Captcha is made of an image and an input.
Captcha is sent with form data on submission and checked server-side.  If needed, I could make a captcha only server-side validation for validating only the captcha string without posting form data.

How could I integrate this captcha to work with surveyjs?

Related: https://github.com/surveyjs/survey-library/issues/882

**Comment by cdalexndr** [comment]
I've managed to make it working with the following:
1. Use a `html` question type with a placeholder element 
2. After form render replace the placeholder with the actual captcha
3. `onServerValidateQuestions` check if captcha is valid (can set error on the `html` question if invalid captcha)
4. `onComplete` add captcha value to `survey.data` and submit

**Comment by andrewtelnov** [comment]
@cdalexndr We have discussed this functionality internally a year or two ago. We have the strong believe that it not the job of SurveyJS Library.

I can agree that there is need in this functionality for many websites and it includes SurveyJS library developers. However, to implement it correctly and we want to do it correctly, this widget should be out of SurveyJS widget.

The typical flow is the following. End-user go to the page to fill survey/form. There are 3 options:
1) The web page requires authorization. The end-user should be login
2) The web page allows to go directly to survey
3) User must go through a captcha widget (the most seldom case) and on success he will be redirected to the page with survey/form

For the third case, the captcha should create the image on the server, check the result on the server and generates URL where the user will be redirected. This URL should be unique for this user and it must be existed for a limited number of time or a user can access it only one time. Otherwise there is no reason for captcha, robots will just go directly to static URL.

We can create a captcha service that generates images and check the answer on our webservice. It is not a problem. However, we can’t code URL generation and routing for other websites. We believe that this functionality is crucial for correct behavior and that is why we decided not to implement it.

Thank you,
Andrew
