### ISSUE TITLE
Looking for guidance on how the CustomWidget component is used in Vue

### ISSUE THREAD

**Issue by stevebering** [surveyjs/survey-library#2062]
I am trying to provide rich components to use as custom widgets in our Vue application. I do not really want to work with vanilla JS in this, because we already have working components that do what I am trying to do. In the source, I can see a CustomWidget component that has a IsVueComponent getter on it.

How is this used? Can I derive from the CustomWidget and implement my question logic there? How is the json formatted to use a custom widget in this method? 

Thanks for your guidance on this

**Comment by tsv2013** [comment]
I've not found the `IsVueComponent` neither in survey-library nor in the surveys-widgets. As far as I remember it's impossible to use a VueJS component as a custom widget.

**Comment by stevebering** [comment]
Sorry, the computed property that I was referring to is not IsVueComponent but hasVueComponent.

**Comment by tsv2013** [comment]
Sorry for delayed response. Yes, we have the `hasVueComponent` - https://github.com/surveyjs/survey-library/blob/master/src/vue/customwidget.vue#L29-L35 property in the custom widget code.

There is no guidance on it because we never used this code in production purposes. Two years ago we have a plans to support native components as custom widgets and this is the ancient artifact.
I'm not sure the `(<any>Vue)["options"]` code works now. You can try to use this approach at your own risk, but I can't guarantee it will work or it will keep working in the future.
