### ISSUE TITLE
Allow to disable adding/removing rows in matrix dynamic question

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2106]
There is no easy way to disable adding/removing rows in matrix dynamic questions. It needs in scenarios when end-user can modify value cells only.
Use these two properties. They are true by default.

```JavaScript
/**
 * Set this property to false to disable ability to add new rows. "Add new Row" button becomes invsible in UI
 * @see canAddRow
 * @see allowRemoveRows
 */
public allowAddRows: boolean;
/**
 * Set this property to false to disable ability to remove rows. "Remove" row buttons become invsible in UI
 * @see canRemoveRows
 * @see allowAddRows
 */
public allowRemoveRows: boolean;
```

**Comment by albam-osorio** [comment]
I used this functionality, but if I initialize the table with all the delete buttons disabled, then when I add a new row, the delete buttons are not drawn even if I have enabled them

**This is my JSON**

{
 "locale": "es",
 "title": {
  "default": "ENCUESTA ANUAL DE SERVICIOS - EAS\r\nFORMULARIO ELECTRÓNICO 2021",
  "es": "ENCUESTA"
 },
 "logoPosition": "right",
 "pages": [
  {
   "name": "Módulo III",
   "elements": [
    {
     "type": "panel",
     "name": "M03C01",
     "elements": [
      {
       "type": "matrixdynamic",
       "name": "TABLA_M03C01_INGRESOS_POR_SERVICIOS_PRESTADOS",
       "title": "1. Ingresos por servicios prestados",
       "defaultValue": [
        {
         "COL_CPCI_CODIGO": "67230",
         "COL_CPCI_CONCEPTO": "Servicio de almacenamiento para mercancías voluminosas",
         "COL_CPCI_VALOR": 1000,
         "COL_CPCI_EDITABLE": false,
         "COL_CPCI_ELIMINABLE": false
        },
        {
         "COL_CPCI_CODIGO": "67240",
         "COL_CPCI_CONCEPTO": "Servicio de almacenamiento de contenedores llenos y vacíos.",
         "COL_CPCI_VALOR": 2000,
         "COL_CPCI_EDITABLE": false,
         "COL_CPCI_ELIMINABLE": false
        },
        {
         "COL_CPCI_CODIGO": "67250",
         "COL_CPCI_CONCEPTO": "Servicio de custodia de mercancías, información en medio físico y magnético y de títulos valores.",
         "COL_CPCI_VALOR": 3000,
         "COL_CPCI_EDITABLE": false,
         "COL_CPCI_ELIMINABLE": false
        },
        {
         "COL_CPCI_CODIGO": "67290",
         "COL_CPCI_CONCEPTO": "Otros servicios de almacenamiento y depósito n.c.p.",
         "COL_CPCI_VALOR": 4400,
         "COL_CPCI_EDITABLE": false,
         "COL_CPCI_ELIMINABLE": false
        }
       ],
       "columns": [
        {
         "name": "COL_CPCI_CODIGO",
         "title": "Código CPC",
         "cellType": "text",
         "readOnly": true,
         "width": "200px",
         "visibleIf": "{row.COL_CPCI_EDITABLE} = false"
        },
        {
         "name": "COL_CPCI_CONCEPTO",
         "title": "Descripción",
         "cellType": "text",
         "isRequired": true,
         "enableIf": "{row.COL_CPCI_EDITABLE} = true"
        },
        {
         "name": "COL_CPCI_VALOR",
         "title": "Valor \r\n(miles de pesos)",
         "cellType": "text",
         "isRequired": true,
         "width": "200px",
         "totalType": "sum",
         "totalFormat": "$ {0}",
         "totalDisplayStyle": "decimal",
         "inputType": "number"
        },
        {
         "name": "COL_CPCI_EDITABLE",
         "cellType": "boolean",
         "readOnly": true,
         "visibleIf": "false",
         "defaultValue": "true"
        },
        {
         "name": "COL_CPCI_ELIMINABLE",
         "cellType": "boolean",
         "readOnly": true,
         "visibleIf": "false",
         "defaultValue": "true"
        }
       ],
       "horizontalScroll": true,
       "cellType": "text",
       "rowCount": 4,
       "addRowText": "Adicionar",
       "removeRowText": "Eliminar"
      }
     ],
     "title": "INGRESOS - Recuerde que los valores deben estar en miles de pesos"
    }
   ],
   "title": "Módulo III",
   "description": "MÓDULO III - INGRESOS, COSTOS Y GASTOS CAUSADOS EN EL AÑO"
  }
 ],
 "sendResultOnPageNext": true,
 "showQuestionNumbers": "off",
 "autoGrowComment": true,
 "showPreviewBeforeComplete": "showAllQuestions"
}

**This is my method that enables or disables the delete button, depending on a hidden field in each row**

  private onMatrixAllowRemoveRow(survey: SurveyModel, options: any) {
    if (
      options.question.name === 'TABLA_M03C01_INGRESOS_POR_SERVICIOS_PRESTADOS'
    ) {
      options.allow = options.row.getValue('COL_CPCI_ELIMINABLE');
      console.log(
        `name:${options.question.name}, options.rowIndex:${options.rowIndex} options.allow:${options.allow}`
      );
    }
  }

**This is how the matrix looks when it is initialized, no button is observed since everything is disabled. Note that by default in the new rows the COL_CPCI_ELIMINABLE field will have a true value and therefore it should be displayed**

![image](https://user-images.githubusercontent.com/22049766/166110274-e493fe98-3995-4709-a6e2-a6f514d5bdb4.png)

**But as you can see this does not happen**
![image](https://user-images.githubusercontent.com/22049766/166110706-679a5166-de60-4980-98e0-91e91e6b0b54.png)

**If I initialize the matrix by enabling the delete button in at least one row**
![image](https://user-images.githubusercontent.com/22049766/166110794-935596fd-b352-4895-8878-8dd79a9c3ce0.png)

**The button appears in the new rows**
![image](https://user-images.githubusercontent.com/22049766/166110812-015e3d2c-0a5a-499e-ba3a-56f86737e3a9.png)

But in my use case the initial rows cannot be deleted

My dependencies
  "dependencies": {
    "@angular/animations": "~12.0.3",
    "@angular/common": "~12.0.3",
    "@angular/compiler": "~12.0.3",
    "@angular/core": "~12.0.3",
    "@angular/forms": "~12.0.3",
    "@angular/platform-browser": "~12.0.3",
    "@angular/platform-browser-dynamic": "~12.0.3",
    "@angular/router": "~12.0.3",
    "rxjs": "~6.6.0",
    "survey-angular": "^1.8.72",
    "survey-pdf": "^1.8.72",
    "surveyjs-widgets": "^1.8.72",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
