### ISSUE TITLE
How to get custom properties on result object

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2207]
I have added some custom properties added to json input for the survey model.
But while getting the the result object, we are getting only question name & choice value.
How to retain those custom properties inside the result object in addition to question & choice value?

**Comment by tsv2013** [comment]
Custom properties are added to survey JSON. It is the object that defines sourvey content and behavior. Survey result contains the answers of a surveyee. And that's why survey result doesn't contain any model settings.

You can add any custom properties using simply JS code: iterating through the questions and changing survey results from simply value to objects containing the value and your custom properties. Or you can completely change survey results format according your needs.
