### ISSUE TITLE
onMatrixAfterCellRender event is not triggering

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2249]
I have a matrix question in my survey. I am trying to `console.log(options)` inside `onMatrixAfterCellRender` event.
But event is not getting triggered, why? is it a bug?

**Comment by tsv2013** [comment]
Can you provide us with a sample illustrating the issue?

**Comment by sem1colon** [comment]
Consider this example..
https://plnkr.co/edit/0YlAeJUVuFYuwhMi
Here, `onAfterRenderQuestionInput` working fine for _radiogroup_, but when I tried the similar way for matrix question, `onMatrixAfterCellRender` is not working.

**Comment by tsv2013** [comment]
The `onMatrixAfterCellRender` event works for the `matrixdynamic` and `matrixdropdown` question types only. For the simple `matrix` question you need to use the `onAfterRenderQuestion` event.

**Comment by sem1colon** [comment]
Then, we have a problem. I am having *visibleIf* condition for matrix columns. So based upon the previous question responses, columns will be visible & hidden. I am trying to add tooltip for columns. I can able to get this at `onAfterRenderQuestion` event, but the problem is when the user changes the previous question responses, only my columns are modified(columns have to render), but the question is already rendered previously. So, I am not able to get hovertext for columns.

**Comment by sem1colon** [comment]
Any solution for that problem?

**Comment by tsv2013** [comment]
Right now SurveyJS doesn't have a solution for this scenario. Please provide us with a working sample illustrating the case and we'll try to find a solution.

**Comment by sem1colon** [comment]
Here's the [example](https://stackblitz.com/edit/surveyjs-matrix-tooltip-problem)
I have *visibleIf* condition for the last row, when that is visible all the existing tooltips will be gone.

**Comment by sem1colon** [comment]
Why is *enableIf* property not available for matrix?

**Comment by tsv2013** [comment]
Thank you for the example. I'll see what we can do with it.

SurveyJS has columnsVisibleIf and rowsVisibleIf properties to show/hide columns and rows in matrix question - https://surveyjs.io/Examples/Library?id=condition-matrixVisibleIf&platform=jQuery&theme=modern

As for cells, the martix question contains unified scale of marks (the columns) and user should select one mark from the given. Each row has the same radiogroup question. Usually all marks should be available (exists) for every row. Otherwise it willn't be comparable to the other rows because of the different scale. So probably this is the other type of question SurveyJS doesn't contain one. At the same time I can't remember it as a highly requested functionality.

**Comment by sem1colon** [comment]
Any update ?

**Comment by sem1colon** [comment]
Okay, we were able to solve this problem by adding some logic in `onValueChanging` event.
Please check the updated [example](https://stackblitz.com/edit/surveyjs-matrix-tooltip-problem).

**Comment by tsv2013** [comment]
Why not? It will work ok if you want to patch all matrix questions on a page.
