### ISSUE TITLE
`clearInvisibleValues: 'onHidden'` makes survey nullify some question values while loading data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2250]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I need to use `clearInvisibleValues: 'onHidden'` (it's a requirement) but when I use `visibleIf` targeting a question whose value depends on some async events I got an undesired behaviour. I created a plunk to show this 

https://plnkr.co/edit/YQxFPTAsv0zgz0R0

If you rerun the survey multiple times you'll see that _foo_ question loses its initial value. Looking at the console you'll see how the survey data evolves. In my understanding there is a moment when copyCountry gets null and, as a consequence, foo gets undefined too. Is this explanation correct? Of course, removing `clearInvisibleValues: 'onHidden'` solves but for me it is essential when the user interact with the survey. To be more precise I don't need it in the "data loading phase" while I need it later during user interaction. I think this survey property can be changed at runtime but how can I know when surveyJS has finished to run all expressions and choicesByUrl stuff and its ready for editing? This leads me again to this old unresolved issue https://github.com/surveyjs/survey-library/issues/1871 

Curiously this does not happen without paneldynamic. 

https://plnkr.co/edit/vaqoo5Xnnwmf1pYZ

Is this all expected?

thanks a lot

**Comment by Lionqueen94** [comment]
Hi team!

I came accross this similar issue.
The `defaultValue` of a field with a `visibleIf` gets removed when `clearInvisibleValues: "onHidden"`.
See the below Plunker:
https://plnkr.co/edit/D5JQ4SaJpa2Ilfwv

When you enter a name, the number field appears but the default value is missing.

I think the clearInvisibleValues should not clear/remove the `defaultValue` of a field. I hope you guys can fix this.
Thanks!

**Comment by gologames** [comment]
Hello,

Let me, please, explain my thoughts about this situation. I thinks there is no way to solve this problem in general case on SurveyJS side. Just because there is an dependency graph (not tree) in general case

E.g. I [modified your plunker](https://plnkr.co/edit/3nnwVds432LztwQq). I set the expression question calculate value equal to text question. And text question visible if expression is not empty. Also clearInvisibleValues on hidden. What we got?

Let's imagine case 1:
1) Set data value to text questions
2) Clear text value due to clearInvisibleValues
3) Copy empty value from text to expression
4) Hide text question due to expression is empty

Otherwise imagine case 2:
1) Set data value to text questions
2) Copy not empty value from text to expression
3) Display text question due to expression is not empty
4) clearInvisibleValues call has no effect

What of this these two cases is true? No answer. There is no right case. So this problem hasn't solution in general case with that amount of information which we have at SurveyJS library side

So as a result I can suggest you process your business logic with various SurveyJS events such as [onValueChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onValueChanged) or [onVisibleChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onVisibleChanged). You can also count loaded questions to detect when survey is loaded according to your business logic

Thanks, Alex
SurveyJS Team

**Comment by masciugo** [comment]
@gologames thanks for your answer but maybe you forgot to save the plunker

**Comment by Lionqueen94** [comment]
@gologames I don't understand what you mean. In my case, having a defaultValue specified and having the field on visibleIf depending on another field, when the field is hidden, there should be no value, but when the field is shown, it should have the defaultValue (if defined). I don't see a problem with this case but please elaborate if there is an issue. When I think back to how this used to work, I think it worked like this and the functionality disappeared some time ago (I would have to test with older survey.jquery file versions to see if I'm correct).

**Comment by gologames** [comment]
> @gologames thanks for your answer but maybe you forgot to save the plunker

True, I saved it now

**Comment by gologames** [comment]
Hello,

> @gologames I don't understand what you mean. In my case, having a defaultValue specified and having the field on visibleIf depending on another field, when the field is hidden, there should be no value, but when the field is shown, it should have the defaultValue (if defined). I don't see a problem with this case but please elaborate if there is an issue. When I think back to how this used to work, I think it worked like this and the functionality disappeared some time ago (I would have to test with older survey.jquery file versions to see if I'm correct).

In your case the situation is absolutely the same as I described above
Imagine this case:
1) Default value is set for question which is hidden due to visible if
2) Value of this question clears due to clearInvisibleValues
3) Then visible if becames true
4) Questions displays with empty data

This is one of valid scenarios. You can use [onVisibleChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onVisibleChanged) event to set question value equal to default value when question will became visible 

Thanks, Alex
SurveyJS Team
