### ISSUE TITLE
Language switching bugs

### ISSUE THREAD

**Issue by w16616668** [surveyjs/survey-library#2319]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

I set the default language to 'zh-tw'. At the same time, 'en' and 'pt' are added to multiple languages. When the language is switched to 'en', 'zh-tw' is still displayed

### What is the expected behavior?

When switching to en, English is displayed

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "locale": "zh-tw",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "width": "200",
     "minWidth": "200",
     "maxWidth": "200",
     "title": {
      "default": "问题1",
      "pt": "pt 1",
      "en": "q1"
     },
     "size": 50,
     "placeHolder": {
      "default": "请填写答案",
      "pt": "pt 1",
      "en": "q1"
     }
    },
    {
     "type": "checkbox",
     "name": "question2",
     "title": {
      "default": "问题2",
      "pt": "pt 2"
     },
     "choices": [
      {
       "value": "item1",
       "text": {
        "default": "啊",
        "pt": "pt 1",
        "en": "a1"
       }
      },
      {
       "value": "item2",
       "text": {
        "default": "啊",
        "pt": "pt 2",
        "en": "a2"
       }
      },
      {
       "value": "item3",
       "text": {
        "default": "啊",
        "pt": "pt 3",
        "en": "a3"
       }
      }
     ]
    }
   ]
  }
 ]
}
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.7.25

**Comment by andrewtelnov** [comment]
@w16616668 You changed the default locale fro "en" to "zh-tw". You should to tell Survey about it as:
``Survey.surveyLocalization.defaultLocale = "zh-tw";`` 
By default the default locale is english. Survey could not find "zh-tw" in your title localization and use "default". That is why it shows correctly for "zh-tw". For "en", it get from "default", since it is a default locale.
When you tell Survey that default locale is "zh-tw" then Survey will look for "en" locale.

Thank you,
Andrew

**Comment by w16616668** [comment]
According to your method, the problem has been solved. Thank you very much!
