### ISSUE TITLE
readOnlyCommentRenderMode doesn't work

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#2352]
based on https://github.com/surveyjs/survey-library/issues/2192#issuecomment-667031856

**Comment by dmitrykurmanov** [comment]
We've fixed the problem. Fix will be available in the next minor release.

**Comment by dmitrykurmanov** [comment]
@ironman1964

I've realized that it was not a bug. We changed the `readOnlyCommentRenderMode` property and now it is global for all survey instances. Here the usage example:

```js
Survey.settings.readOnlyCommentRenderMode = "div";
```

**Comment by andrewtelnov** [comment]
@ironman1964 If you want to have NewLines that works like in textArea, then why don't you use text area? :-)
You can customize it using CSS, so it looks like div in read-only mode, remove borders and so on.
It would be easy to impelment. Otherwise, you will have to proccess the text and insert <p> or <br/> tags.

Thank you,
Andrew
