### ISSUE TITLE
How to perform clean remove/destroy

### ISSUE THREAD

**Issue by fabien** [surveyjs/survey-library#241]
I'm using the jQuery version, and I was hoping to find a method to cleanly destroy a Survey instance - unbinding any event handlers and so on:

```
$('#survey').Survey('destroy')' // or:
survey.destroy();
```

Care should be taken, so all DOM event handlers etc. are disposed to prevent any memory leaks in a SPA setup.

**Comment by andrewtelnov** [comment]
@fabien Unless I am not mistaken, we do not have this functionality yet, for jQuery version. @dmitrykurmanov and @tsv2013 lets discuss this tomorrow.

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
Hi guys,

Have any improvements been made regarding this? 

What would be the best way to dispose of surveyjs in an angular cli app?

Moreover we have many different survey json models that we need to display at runtime depending on current selection so is there any best practice to replace current surveyjs model?

Thanks,
Hristo

**Comment by dmitrykurmanov** [comment]
Hello! Sorry for the late response. What functionality do you want to achieve? May be `document.querySelector("#SurveyElement").innerHTML = ""` will ok for you?

**Comment by fabien** [comment]
Hi @dmitrykurmanov! setting `innerHTML` is not really the same thing. A proper `destroy` method should be implemented to dispose any DOM event handlers and so on, so a SPA doesn't leak memory every time a new survey is created (and an old survey is not properly discarded).

**Comment by dmitrykurmanov** [comment]
Hello @fabien I understand. I think that SurveyJS doesn't have any DOM event handlers outside the root (#SurveyElement) node. So setting innerHTML to empty string should remove all inner nodes and lead to surveyjs model recycling by garbage collector (because there is no more references to the surveyjs model from outside the root surveyjs markup node). But I can miss something. Could you please provide an example with memory leaks. We will check it.

**Comment by halexiev-hedgeserv** [comment]
Hi @dmitrykurmanov,

Here's our case - we load dynamically the surveyjs json model, so given that we are using angular cli we could not think of something better then the following whenever we need to feed surveyjs the new model:

```
private reloadSurveyjsComponent() {
    if (this.surveyjsHost) {
      if (this.transactionEntryDocumentModel == null) {
        this.surveyjsHost.viewContainerRef.clear();
      } else {
        let componentFactory = this.componentFactoryResolver.resolveComponentFactory(SurveyjsComponent);
        this.surveyjsComponentRef = this.surveyjsHost.viewContainerRef.createComponent(componentFactory);
        this.surveyjsComponentInstance = this.surveyjsComponentRef.instance as Surveyjs;
        this.surveyjsComponentInstance.model = this.transactionEntryDocumentModel.data;

        if (this.transactionEntry && this.transactionEntry.data) {
          this.surveyjsComponentInstance.data = this.transactionEntry.data;
        }
      }

      this.changeDetectorRef.markForCheck();
    }
  }
```

So basically we wrap surveyjs in a dynamic angular component which we recreate along with surveyjs inside it when setting the new json model.

**Comment by tsv2013** [comment]
@halexiev-hedgeserv Could you provide us with a minimal complete example (https://stackoverflow.com/help/mcve) in a separate project or based on our https://github.com/surveyjs/surveyjs_angular_cli repo in order to reproduce the issue on our side and fix it?

**Comment by halexiev-hedgeserv** [comment]
Hi @tsv2013,

There is no real issue to fix I think. 

There is, however, new functionality to implement maybe or at least a need for a real example that shows how to dispose surveyjs once rendered with some json model.

What I provided in my last comment is what we currently do in order to reload/refresh surveyjs when there is a new json model in an angular cli environment. This may or may not be best way to do it, but your  angular cli repo (https://github.com/surveyjs/surveyjs_angular_cli) does not have  such an example, so this is what is working for us at the moment. 

What's more - I find your angular cli repo quite outdated to say the least. I mean TS version there is 2.4.2 whereas angular 5 supports 2.6.x already. The Angular version is also quite old as well - 5.0.0 whereas latest version as of today is 5.2.9.

This is an issue for us because some things do not really work like you have it there in the repo with TS v.2.6.2 and Angular v.5.2.9 like the way you import widgets, for example.

If anything comes out of this issue I  would greatly appreciate if you update your angular cli repo more often so that it is much closer to latest versions of TS and Angular.


Thanks,
Hristo
