### ISSUE TITLE
Default value is cleared for 'Select All' when loading choice from web

### ISSUE THREAD

**Issue by Tri125** [surveyjs/survey-library#2493]
### Are you requesting a feature, reporting a bug or asking a question?

Bug(?)

### What is the current behavior?

I'm trying to set a checkbox question where the valued are loaded from an api and make all values selected by default.

I added a 'Select All' choice and made it selected by default. However, this only work if the url doesn't template from another question answer. If part of the url is composed from another question, after answering that question 'Select All' will be cleared.

### What is the expected behavior?

I would expect 'Select All' to stay selected whether or not the url is templated from the answer of another question.

### How would you reproduce the current behavior (if this is a bug)?

Check the test page.

#### Provide the test code and the tested page URL (if applicable)

Test page URL:

https://plnkr.co/edit/gphgNxF8ednGjShF

question2 display the correct behavior when the url doesn't use templating.

question1 depends on the answer of q0 and will display the problem where 'Select All' will become unselected.
![5fIL1RkHVD](https://user-images.githubusercontent.com/2048645/97320824-99140180-1844-11eb-8261-23dc46f7851f.gif)

### Specify your

* browser: firefox
* browser version: 81.0.2
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.9

**Comment by andrewtelnov** [comment]
@Tri125 It works absolutely correctly, IMHO.
Let's say you have checkbox with 3 choices, you click "Select All", it selects all 3 choices. Then you are adding the 4th choice. It is unselected by default. When you click "Select All", you did not have this choice and you may don't want to select it. Question behaviour is correct, it adds  a choice, makes it unselect and then unselect "Select All", since not all choices are selected.
We do not change question.value on adding new choices, that would be a bug.

Thank you,
Andrew

**Comment by Tri125** [comment]
Alright thank you. I implemented a custom behavior on my end to accomplish this.
