### ISSUE TITLE
What is the correct use of the hideRequiredErrors property?

### ISSUE THREAD

**Issue by alfredodelfabro** [surveyjs/survey-library#2601]
Hello, I have a question about using the hideRequiredErrors property. I tried to use it but the survey alert remains showing when I don't fill any questions marked with isRequired: true. Can you explain the correct use?

Related question: https://surveyjs.answerdesk.io/ticket/details/t2692/how-can-i-suppress-the-default-survey-js-error-text-please-answer-the-question#

**Comment by andrewtelnov** [comment]
@alfredodelfabro If you set this property to true, then it will hide the error text, but error will be still there. In the modern theme we highlight the question with errors in red. Since for a requried question there is a '*' sign in the title, some developers don't want to show additionally a required error text, since they believe their users understand what is wrong without error text.

You are probably lookig for [survey.checkErrorsMode](https://surveyjs.io/Documentation/Library?id=surveymodel#checkErrorsMode). For example, if you set it to "onComplete", than survey will start to show errors when a user press a "Complete" button. It will navigate to a page with the first error, if needed.

Thank you,
Andrew

**Comment by alfredodelfabro** [comment]
Thank you @andrewtelnov!
