### ISSUE TITLE
Feature request: html descript for panel/questions

### ISSUE THREAD

**Issue by edgar-koster** [surveyjs/survey-library#2618]
Currently the `description` of a panel and or question isn't in html. It does allow markdown. I would like that the description also supports html. All the options for this are included already in the library (e.g. you also have a html question, survey html completion etc). It is very common you might want to link to some more information or help, or add some line breaks in the description you enter.

Can this be implemented

**Comment by andrewtelnov** [comment]
@edgar-koster description supports markdown. Here is [the example](https://plnkr.co/edit/XKuQRFBd9oNh9mtf).

Thank you,
Andrew

**Comment by edgar-koster** [comment]
Hi Andrew
I know it supports markdown. The thing is, when I first had that in our surveys it wasn't sufficient due to what it was needed for and the there was always the fact there was a difference between the entering and result. Otherwise I'ld have stuck with that. I understand if this the choice of surveyjs, then I'll think of something else.

**Comment by andrewtelnov** [comment]
@edgar-koster We will not add support for html rendering for description or other property because of security.
You can add a new property and hide the current description property as:
`Survey.Serializer.add("question", {name: "htmlDescription:html", category: "general"});` 
and then use `survey.onAfterRenderQuestion` event, here is the [example](https://surveyjs.io/Examples/Library?id=survey-afterrender).

Thank you,
Andrew

**Comment by edgar-koster** [comment]
Okay thanks Andrew. 
The example is even exactly what I was looking for a next item: a more information option for radio and checkbox options.
