### ISSUE TITLE
Progress buttons with onServerValidateQuestions issues

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2619]
Hi there!

Sorry to bother you again, but I have found 2 more issues with `"progressBarType": "buttons"`.
When `onServerValidateQuestions` is implemented (with setting `"checkErrorsMode": "onValueChanged"` for example or at least not on `"onComplete"`:
1. The passed progressNavigationButtons do not get the class `sv_progress-buttons__list-element--passed`.
2. When you are on the 1st page and click on the 3rd page, surveyjs sends you to the 2nd page.

I have been able to reproduce it in this Plunker:
https://plnkr.co/edit/lJLvVsRbuBDvK21V

As you can see in the above Plunker:
1. When you go to a next page, the class is not applied to the buttons of the previous pages.
2. Click on the Contacts page when you are on the Satisfaction page and see that you end up on the Pricing page instead of the Contacts page.

P.S. @gologames If you want me to create a new issue, I will, just let me know :+1:

_Originally posted by @Lionqueen94 in https://github.com/surveyjs/survey-library/issues/2608#issuecomment-762271646_

**Comment by gologames** [comment]
Hello,

We fixed setting correct passed page style in case of `onServerValidateQuestions` is set via commit mentioned above. At the same time there is some conceptual trouble with navigation though many pages in this case. Assuming that validation will performed on the server, then this is an asynchronous function. As a result in the moment of click we cant going next page

We can try to find solution. Maybe via adding event callback when click on navigation button, storing the number of page and then continuing navigating in `onServerValidateQuestions` event. But is this really important feature for you?

Thanks, Alex
SurveyJS Team

**Comment by Lionqueen94** [comment]
Hi @gologames,

Thanks for the fix! I'm excited to test it out when it's released.

I understand the navigation trouble, this is for sure not easy to fix. Is it possible to disable clicking/hovering over the page buttons after the next page? So that the user will not be confused when he clicks on a page and the survey will just go to the next page instead of the clicked page.

In my production, our customers have to fill in the survey page by page, with validation on each page before continuing. For my admin colleagues, I have the validation onComplete, so they can traverse the pages at will. I don't want to make it more difficult for the customers, so disabling the page buttons you cannot go to yet would be a good solution for me. Let me know if this would be possible or if it can be a certain setting in the json for example.

Thanks a lot for all the work so far!

**Comment by gologames** [comment]
Hello,

We implemented progress buttons non clickable in case of `onServerValidateQuestions` event is set via commit mentioned above. This will available with next minor update

![image](https://user-images.githubusercontent.com/30930391/105838761-98c10900-5fe1-11eb-9750-39067d78a6ab.png)

![image](https://user-images.githubusercontent.com/30930391/105838801-a5456180-5fe1-11eb-8260-e7666e0831d3.png)


Thanks, Alex
SurveyJS Team

**Comment by Lionqueen94** [comment]
Hi @gologames,

The new release works perfectly, thanks for the fixes! This issue can be closed now.
Btw, I see that milestones are sometimes not added to fixed issues, this makes it difficult for other users to see if something was fixed in a certain version. Just something I noticed, thanks for the good work!

Regards,
Ellen
