### ISSUE TITLE
choicesFromQuestion and select2 with tags: true

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2632]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

Before _choicesFromQuestion_ feature was added I had my own custom widget that, among other things, already did that. Now I want to simplify it by removing some code and leveraging the new feature

My custom widget is very similar to the official select2-tagbox.js. It let you add tags and I want to make them visible to the dependedQuestions. 

In the following plunker 

https://plnkr.co/edit/bdpzQvf7UMWTUW7p

I simply added `question.updateChoicesDependedQuestions()` at customwidget.js:57. It partially works: the first tag I add in q1 does not get visible in q2 but by the second one they all do.

Could you help please? tnx

**Comment by andrewtelnov** [comment]
@masciugo Probably I missed something, but it works perfectly to me. I add the first tag into "q1" and it becomes immediately available in "q2". Did you change anything?

Thank you,
Andrew

**Comment by masciugo** [comment]
Hi andrew. I meant a custom tag that is one not present in the q1 default options but added manually. thank you

**Comment by andrewtelnov** [comment]
@masciugo Man, here is your mistake:
```js
survey.data = {
    q1: ['Andorra'],
};
```
Instead of
```js
survey.data = {
    countries: ['Andorra'],
};
```
Thank you,
Andrew

**Comment by masciugo** [comment]
Thank you Andrew but the initial data was forgotten and has nothing to do with my problem (I removed it). If you add a custom choice in q1 (at runtime) you'll not find it among q2 choices

**Comment by andrewtelnov** [comment]
@masciugo It works fine in your example as I see. Here is [the updated example](https://plnkr.co/edit/4qSoA6n6kaSX8e1p). "Andorra" set in "q1" and "Andorra" in the dropdown of "q2" question.

Thank you,
Andrew

**Comment by masciugo** [comment]
Sorry again I think I was not been able to explain. instead of Andorra try adding "sicily" or anything else missing in q1 choices... you can add sicily to q1 and select it but it will not be added to q2 choices. hope it's clear now

**Comment by andrewtelnov** [comment]
@masciugo Here is [the example](https://plnkr.co/edit/YTxZ9n8VELtO7adX) that works. You added "Sicily" early, before getting results from the server and when results came from the server, "Sicily" is erased by data that comes from the server.

Thank you,
Andrew

**Comment by masciugo** [comment]
Yes but I'd like to add tags at runtime. Here my plunk behavior: 

https://user-images.githubusercontent.com/454321/106440424-220c8b80-6479-11eb-9f35-d5e7827672c7.mov

**Comment by masciugo** [comment]
I updated my plunk to sjs 1.8.36: https://plnkr.co/edit/6zM1I0MXk6lHB7H8

I dug deeply into surveyJS code and I noticed that the problem is inside `QuestionSelectBase.prototype.getChoicesFromQuestion` which should return the added tag too (foo in the previous screen recording) but even if it's inside `q1.visibleChoices` it does not seem selected to surveyJS because q1.isItemSelected("foo") return false! And this because `q1.activeChoices` is not sync with `q1.visibleChoices` 

I had to manually align them to have it working. See line 56 in the following plunk
https://plnkr.co/edit/Quv3Dnhm6ed1GoUI

Of course I don't like all this internal hacking but, please, can you just tell me what's the difference between activeChoices visibleChoices and filteredChoices? Do you think my code is robust enough? 

thanks

**Comment by andrewtelnov** [comment]
@masciugo Yes, it looks overcomplicated. I need to ask our technical writer to expain it.
So, we have public properties `choices` and `choicesFromQuestion`,  and private `choicesFromUrl`. Based on these properties the question caculate `activeChoices` using the following logic: if `choicesFromQuestion` not empty then get choices from another question, otherwise check if `choicesFromUrl` is not empty then use `choicesFromUrl` otherwise use `choices` property.

The we have filteredChoices it is activeChoices filtered by `choicesVisibleIf` property in the question or using `visibleIf` property in the choices.
If there is no filtering then we create `visibleChoices` by using `activeChoices` property or otherwise `filteredChoices`. After we copy these items into `visibleChoices` we do sorting, if needed, and add 'None', 'Other' and 'SelectAll' items.
If there is no sorting and there is no additional items, then we do not copy items into new array, but use `activeChoices` or `filteredChoices` as it is.

Thank you,
Andrew

**Comment by masciugo** [comment]
I ended up overriding renderedValue to question targeted by _choicesFromQuestion_ so that it's value does not contain _other_. thank you
