### ISSUE TITLE
Update guide

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [surveyjs/survey-library#2763]
Hello,
I have an application that has an old version of the library - 1.0.56. 

I am estimating the effort for updating it to the latest version, but the changelog document isn't very helpful. Apparently, for the past 3 years, there have only been bugfix releases.

This means that one could simply install the latest version and be done with it. Can this be expected?

Otherwise, it would be nice to have a list of breaking changes.

**Comment by andrewtelnov** [comment]
@nemanjamilosavljevic-newtron It depends how deeply you customize our widgets.
We are fully, 100%, compatible on JSON level. All JSON from very old Beta versions are working with the latest version.
The biggest changes are html rendering and CSS. If you do E2E testing, then you will need to update your functional tests.
We added a ton of new functionality, make sure that our libraries are working with latest frameworks versions (react, knockout, vue). It means that probably you will need to update other libraries up to date.

PS: We did not test our libraries with vue 3 yet. Because the recomended version to use is vue 2.6.12 right now. As soon as it becomes v3, we will update our library accordingly.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Change list can be found here - https://surveyjs.io/WhatsNew

**Comment by nemanjamilosavljevic-newtron** [comment]
Thanks for the information guys. 
I wish I would have found the WhatsNew myself. How can I reach that link myself? It's not on the https://surveyjs.io/.

**Comment by andrewtelnov** [comment]
@nemanjamilosavljevic-newtron We do not name it as What's new. It is a link on the top left corner, [v 1.8.39-->](https://surveyjs.io/WhatsNew).

Thank you,
Andrew
