### ISSUE TITLE
"There is no visible page or question in the survey" flashes before survey loads

### ISSUE THREAD

**Issue by DanielDwyer** [surveyjs/survey-library#2944]
### Are you requesting a feature, reporting a bug or asking a question?
I am reporting what I see as a bug, due to the fact that I do not see documentation on how to hide or customize the "There is no visible page or question in the survey" message. How can I suppress the "There is no visible page or question in the survey" from displaying when it shouldn't/when loading? Thanks in advance!

### What is the current behavior?
As the survey loads, the "There is no visible page or question in the survey" flashes (ever so briefly). Here is a link to a Loom example of this bug: [Loom Example](https://www.loom.com/share/f4b6401f8a4d44598fc69f3513619d67)

### What is the expected behavior?
The "There is no visible page or question in the survey" message should not flash if there are questions but they simply are not fully loaded yet.

### How would you reproduce the current behavior (if this is a bug)?
Load any survey.

### Specify your

* browser: Chrome
* browser version: Chrome91
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version:  1.8.46

**Comment by andrewtelnov** [comment]
@DanielDwyer If you are loading survey JSON from our service, then SurveyJS can handle it and show `survey.loadingHtml` text. If you load from your own service, then SurveyJS can't do nothing because SuveyJS is not aware that you are going to set survey json later. It shows what it have now.
The easiest solution, is to show your own html elements with any message you want while you are loading JSON, the on loading JSON hide the "loading" message and create/show the survey or show error in case of any.

Thank you,
Andrew

**Comment by DanielDwyer** [comment]
I see, I am loading from my own service. Thanks for the info.
