### ISSUE TITLE
Support "parentpanel" in expression for nested dynamic panels

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#3491]
If there is a nested dynamic panel (dynamic panel inside another dynamic panel), then to access values in expression from the parent panel can by using "parentpanel" prefix.
Here is the JSON example. "child_question1" becomes visible when an user set any value into checkbox_root question and child_question2 shows choices that selected in checkbox_root.
```js
{
      elements: [
        {
          type: "paneldynamic",
          name: "rootPanel",
          panelCount: 1,
          templateElements: [
            {
              type: "checkbox",
              name: "checkbox_root",
              choices: ["item1", "item2", "item3"],
            },
            {
              type: "paneldynamic",
              name: "childPanel",
              minPanelCount: 1,
              templateElements: [
                {
                  type: "text",
                  name: "child_question1",
                 visibleIf: "{parentpanel.checkbox_root} notempty"
                },
                {
                  type: "checkbox",
                  name: "child_question2",
                  hideIfChoicesEmpty: true,
                  choicesVisibleIf: "{parentpanel.checkbox_root} contains {item}",
                  choices: ["item1", "item2", "item3"],
                }
              ]
            }
          ]
        }
      ]
    }
```

**Comment by masciugo** [comment]
Hi @andrewtelnov thanks for this enhancement. I was about to implement something similar through a custom function when I bumped into this new feature. I would like to share my vision with you. 
I usually tend to treat both dynamic elements (paneldynamic and matrixdynamic) similarly because the produce the same data structure (an array of objects). In both types of questions those objects has a parent. Having said that, even if you cannot have a matrixdynamic inside a matrixdynamic you can have a matrixdynamic inside a paneldynamic. And you may need to access the outer panel from inside the matrixdynamic row. 

So I was thinking to implement that kind of parent access for both and I would call it generally _parentQuestion_ (based on [this](https://surveyjs.io/Documentation/Library?id=questiontextmodel#parentQuestion)) which should work inside paneldynamic panels and matrixdynamic rows. 

What do you think?

**Comment by andrewtelnov** [comment]
@masciugo Could you please share a very simple JSON: paneldynamic wth matrixdynamic inside it and expression. Probably several scenarios. I'm not sure I full understand the issue right now.

Thank you,
Andrew

**Comment by masciugo** [comment]
Here it is https://plnkr.co/edit/EPxqgkXoOxyDqWkv

**Comment by andrewtelnov** [comment]
@masciugo It should be "parentPanel" and not "parentQuestion" in your case.

Thank you,
Andrew

**Comment by masciugo** [comment]
I tried with that but it does not work

https://plnkr.co/edit/JwmHv2rIFamuzNGg

But I actually expected it because matrixdynamic may not necessarily live in a panel... parentQuestion is what I would call to reach the parent question from a data point of view: a level up in the json of the data

**Comment by masciugo** [comment]
I [updated the plunk to 1.8.79](https://plnkr.co/edit/xsOqq5i8qOthFaGX) but still not working with matrixdynamic inside paneldynamic

**Comment by andrewtelnov** [comment]
@masciugo In your case the following [example](https://plnkr.co/edit/tBkexLsPqNmnIdro) should work. Unfortunately, it doesn't. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the issue by the commit above. {panel.region} will work for your example.

Thank you,
Andrew
