### ISSUE TITLE
`<legend>` is only added to `<fieldset>` with checkboxes, but not for radio group

### ISSUE THREAD

**Issue by dszewczyk1** [surveyjs/survey-library#3765]
It seems that `<legend>` is only added to `<fieldset>` with checkboxes, but not for radio group?

_Originally posted by @dszewczyk1 in https://github.com/surveyjs/survey-library/issues/1445#issuecomment-994875491_

**Comment by dmitrykurmanov** [comment]
Yes, we did some work for better accessibility in `radiogroup`. And we have plans to do the same work for other question types. But for now, we have some differences between `radiogroup` and other question types.

As for `fieldset` and `legend`. We have a very custom layout for our questions and for accessibility purposes we should use custom "aria" attributes instead of native HTML markup (fieldset with the legend first child inside and so on).

So we use [role="presentation"](https://github.com/surveyjs/survey-library/blob/6a153cfcb8f148169c55a8602f7dd917a7469e55/src/react/reactquestion_radiogroup.tsx#L36) for radiogroup's fieldset and accessibility tools just ignore it.

Instead of that, we use the properly `aria-label` so it should pass all checks from the accessibility tools and also should sound well on screen readers.

If you have any problem with passing checks or with the screen readers for `radiogroup` please report us. And we'll fix it as well.

Thanks
