### ISSUE TITLE
Multiple file upload ambiguous `onClearFiles`

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4189]
### Are you requesting a feature, reporting a bug or asking a question?
Bug / feature

### What is the current behavior?
When using a multiple file upload question you get a "Remove this file" link beneath each preview.
Clicking it triggers the `onClearFiles` event with these options:
```json
{
  "fileName": "test.jpg",
  "name": "question1",
  "value": [
    { "name": "test.jpg", "type": "image/jpeg", "content": "implementation specific, we use a UUID" }

  ]
}

```
The `fileName` field is set to the file name of the file to be removed, or to `null` if the big "Clean" button is clicked.

### What is the expected behavior?
We should be able to identify which file we have to remove. In most cases the filename will suffice, but it is still a leaky abstraction.
If you select the same file twice (or files with the same name) you are not able to identify which one should be removed.

Ideally the whole value object of the file to be removed should be passed to the event.

### How would you reproduce the current behavior (if this is a bug)?
- Create a survey with a file question that allows multiple files.
- Pick the same file twice
- Click `remove this file` on one of the files
- Try to identify which one you clicked in the event hander for `onClearFiles`

### Versions

- platform: knockout
- version: v1.9.22

**Comment by marvin-wtt** [comment]
Did you find a solution or workaround?
I'm facing the same problem with dynamic panels and file upload.

This is a dummy survey for reproduction:

```json
{
 "title": "Test",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "parent",
     "templateElements": [
      {
       "type": "file",
       "name": "file",
       "isRequired": true
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by marvin-wtt** [comment]
With the example survey I provided, it does not work for me that way:
 - When a single file is removed, `options.filename` contains the name of the file and `options.value` is an empty array. (Or whatever file(s) are remaining). This why, I can filter for files with the same filename and remove those. This works, unless the user uploaded a file with the same name to the question in a different panel. In this case, there is - to my knowledge - no way to find out from which panel the file is removed, since `options.name` is identical.
 - When I press the erase button (clear all), the event is fired but `options.filename` is `null` (even though the type does not allow `null`). Since `options.value` is `null` as well, there is no way of knowing which panel the question belongs to because `options.name` is the same for all panels.
 - The third kind of event is fired when the entire panel is being removed. In this case, `options.filename` is `null` too, but `options.value` still contains all files. This way, I do know exactly which files to remove.
 - When a question is created, a clear event is fired as well, but this event can be filtered as `options.value` is `undefined`.

It would be nice if there is any way of uniquely identifying the file which is being removed. I tried to assign a UUID to the content of a file, but this does not work as I couldn't find a way to access the content in the clear event. I can't find it by process of elimination with the remaining `options.values` either, since `options.values` shows the files for the question in the current panel only and I can't find a way to get some sort of unique panel ID that does not change when panels are removed.

**Comment by JaneSjs** [comment]
Hello @marvin-wtt,
Thank you for the update. To focus on your particular usage scenario, I extracted your recent comment to a separate thread.
https://github.com/surveyjs/survey-library/issues/7045

Please refer to it for futher correspondence.
