### ISSUE TITLE
Survey is not rendered on first page load when creator is present in vue/nuxt project.

### ISSUE THREAD

**Issue by synesthete** [surveyjs/survey-library#4405]
### Are you requesting a feature, reporting a bug or asking a question?
Bug.

### What is the current behavior?
Survey contents are not rendered on the page. The header is present, but the sv-body div is not. 
A reload of the page properly renders the survey. 

### What is the expected behavior?
The survey to be rendered on the first load of the page it is part of.

### How would you reproduce the current behavior (if this is a bug)?
We have noticed this bug only when the survey-creator-knockout module is also present.

nuxt is set with ssr: false

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
<template>
  <client-only>
    <Survey :survey="survey" />
  </client-only>
</template>

<script>
import "survey-core/modern.min.css";
import { StylesManager, Model } from "survey-core";
import { Survey } from "survey-vue-ui";

StylesManager.applyTheme("modern");

const surveyJson = {
  title: "Note",
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "panel",
          name: "panel1",
          elements: [
            {
              type: "text",
              name: "date",
              title: "Date",
              inputType: "date",
            },
            {
              type: "dropdown",
              name: "duration",
              title: "Duration",
              choices: [
                "15min",
                {
                  value: "item2",
                  text: "30min",
                },
              ],
              hasOther: true,
            },
          ],
        }
      ]
    },
    {
      name: "page2",
    },
  ],
  showQuestionNumbers: "off",
};

export default {
  name: "BasicSurvey",
  ssr: false,
  components: {
    Survey,
  },
  data() {
    const survey = new Model(surveyJson);
    survey.onComplete.add(this.alertResults);

    return {
      survey,
    };
  },
  methods: {
    alertResults(sender) {
      const results = JSON.stringify(sender.data);
      alert(results);
    },
  },
};
</script>


```

### Specify your

* browser: Firefox & Chrome
* browser version: 100.0.2 & 102.0.5005.61
* surveyjs platform (angular or react or jquery or knockout or vue): vue ( 2.6.14 ) on nuxt ( 2.15.8 )
* surveyjs version: 1.9.33

**Comment by andrewtelnov** [comment]
@synesthete I have answered on our support forum. It is for all others.
When using "survey-creator-knockout", then it should be used "survey-vue" packages instead of "survey-core" and "survey-vue-ui". "survey-vue" package is a bundle for "survey-core" and "survey-vue-ui".
"survey-core" instance is used by "survey-creator-knockout" and "survey-vue-ui" and knockout should change "survey-core" objects prototypes to make their properties observable. After that "survey-vue-ui" can't work with these objects.
"survey-vue" has it's own internal "survey-core" instance and as result it works fine.
So you have to remove "survey-vue-ui" from the package, add "survey-vue" and change the import:
as:
```import { StylesManager, Model, Survey } from "survey-vue";```
instead of using "survey-core" and "survey-vue-ui"

Thank you,
Andrew
SurveyJS Team
