### ISSUE TITLE
add url href to expression 

### ISSUE THREAD

**Issue by go-sudo** [surveyjs/survey-library#4530]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

Link plain text

### What is the expected behavior?

add url href to expression 

from 
http://www.company.com/showOrder.php?order=4621047
to
<a href="http://www.company.com/showOrder.php?order=4621047" target="_blank">Click to Download</a>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/RqVpdiuKU5RPRbVw

Test code

```
your_code_here

```

### Specify your

browser:Chrome
browser version:Version 102.0.5005.115 (Official Build) (64-bit)
surveyjs platform jquery
surveyjs version:1.9.2

**Comment by andrewtelnov** [comment]
@go-sudo You have to use html question.
You can plase into url a link as {yourQuestionOrCalculatedName}. 
Please review [the following example](https://surveyjs.io/Examples/Library?id=survey-processtext).
You can use html question and set it's html property instead of completedHtml.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Great!

Andrew
