### ISSUE TITLE
none now appears before other

### ISSUE THREAD

**Issue by matthewberryman** [surveyjs/survey-library#4820]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

None now appears before other:
![188373392-716caf27-b26b-4fcc-8510-6f46ae78308c](https://user-images.githubusercontent.com/2288238/189462210-2e687a61-2d84-4daa-8184-28e9c20b0a1f.png)

### What is the expected behavior?

None appears as the last option

### How would you reproduce the current behavior (if this is a bug)?

Have a question with 
```json
      "hasNone": true,
      "hasOther": true,
```

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/sRtm2OHz4hM1twH9

### Specify your

* browser: chrome
* browser version: 106.0.5249.30
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: v1.9.35

Bug seems to have been introduced after v1.9.29

**Comment by JaneGaid** [comment]
Hello,
The Other option is actually displayed at the end of the list because this option follows the text input area. 

If you wish to display the None option at the last position, you can disable the `hasOther` option and create a custom `Other` Text/Comment question and toggle its visibility withthe [visibleIf](https://surveyjs.io/Documentation/Library?id=Question#visibleIf) option. 
```
"elements": [
    {
      "type": "checkbox",
      "name": "car",
      "title": "What car are you driving?",
      "isRequired": true,
      "hasNone": true,
      "hasOther": false,
      "colCount": 4,
      "choices": [
        "Ford",
        "Vauxhall",
        "Volkswagen",
        "Nissan",
        "Audi",
        "Mercedes-Benz",
        "BMW",
        "Peugeot",
        "Toyota",
        "Citroen",
        "Other"
      ]
    },
    {
      "type": "text",
      "name": "otherinfo",
      "title": "Other (describe)",      
      "visibleIf": "{car} contains 'Other'"  
    }
  ],
  "showQuestionNumbers": false
```
[Example](https://plnkr.co/edit/oOCKLCrQ3xXzh1SX).
