### ISSUE TITLE
Concurrent surveys

### ISSUE THREAD

**Issue by brydko** [surveyjs/survey-library#496]
Hello. I would like to express a feature I've been trying to pull out and hear your comments.

The idea is to make several users to fill one survey in a concurrent fashion. I know it will cause massive usability problems, collisions and generally corrupted output. I my context I'm trying to avoid this by letting know the users that they should not edit same questions. The idea is that different users edit different pages.

The concept may sound confusing, but it makes sense filling very huge surveys and / or if they need to be filled quickly. Allowing several users to edit the survey certainly helps in this matter.

These are the issues I've found in my initial implementation:

**Example concurrent survey**
There are 2 users. 
The survey contains 2 pages: 1st contains 5 questions and 2nd contains 8 questions.
User Nº1 fills 1st page
User Nº2 fills 2nd page
Results are saved in the DB on pressing button or switching pages.

User 1 enters the survey and fills out 2 out of 5 questions on page 1  
User 2 enters afterwards, retrieves 2 already answered questions on the page 1 and fills out 3 questions on page 2

here is where the issue appears - 

At this point whatever change will be made by user 1 it will overwrite the whole survey producing an inconsistent result because he is unaware of changes made by user 2.

Also if the user 2 saves his own results, the changes made by user 1 will be overwritten.

I was trying to synchronize the answers to save between users and they keept overlapping. The way I see it there are 2 possible solutions:

1) Solution 1  -  save only the questions you have answered. Use `survey.onMatrixCellValueChanged` to generate a JSON of questions you have changed (instead of using `model.data`). When it comes to saving you've got to use `$.extend(savedSurvey, myCurrentSurvey);` to merge the JSON obtained from the DB (savedSurvey, - answers from page 1) and your own answers (myCurrentSurvey).

2) Solution 2 - obtain the actual Diff of saved JSON (retrieved from DB) and your own JSON (your current status) and save it to the DB. The problem of this approach is that deep-diff may cause issues, There are projects such as [https://github.com/flitbit/diff](https://github.com/flitbit/diff) and [https://github.com/benjamine/jsondiffpatch](https://github.com/benjamine/jsondiffpatch) which allow you to get the descriptor of the difference between JSON objects, but not the diffed JSON itself.

Anyway, the issue seems to be able to distinguish between states of the survey at any given moment. The solution is to keep track of the changes you have made to partially answered survey. For example if you retrieved a survey with few questions already answered, the data you should save is the questions you have answered (or modified) yourself.

What's your thoughts on this ?

Thank you

**Comment by andrewtelnov** [comment]
@Kuhax Yes, it is sounds interesting. However, to be honest, I would like do not to work on it, since there are many other tasks on the list.
If I do it myself, I would it in reactive way. Get the notification on the client about changing happened on the server and show the changes/data immediately.
I would love to work on it, but unfortunately have to work on other, not so cool, but more requested functionality.

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov I agree that this feature will not be widespread since it's scope is limited to certain scenarios, but certailnly it will be nice to see it implemented someday. However I just wanted to share my thoughts about this matter (hopefully it may interest other guys out there).

Meanwhile I'm going to try to tinker and make some research on my own. I'll let you know if some meaningful results are reached. And certainly I'll try to put together a demo showing (at least) what I'm aiming to achieve.

Thank you
