### ISSUE TITLE
Survey library and creator conflict in a Vue app

### ISSUE THREAD

**Issue by BrevAlessio** [surveyjs/survey-library#5176]
### Are you requesting a feature, reporting a bug or asking a question?
Bug
The root cause of this is related to #5097   which has been solved just by preventing the symptoms of the problem, not addressing the real problem. 

### What is the current behaviour?
A Vue application that loads both Survey creator and Survey library, in different pages, receives an error while rendering a survey. The error occurs in this `page.vue` line 4, it states that page.cssClasses.page is undefined, therefore can't access description.
 
`<div v-if="showDescription" :class="page.cssClasses.page.description">`

Please note that the root cause of the error is deeper, it only appears if I my application imports both  libraries.

### What is the expected behavior?
That I can run Survey creator and Survey library in the same application without errors.

### How would you reproduce the current behavior (if this is a bug)?
Navigate the 2 pages of this [Codepen](https://codesandbox.io/s/surveyjs-creator-vue-forked-7b7s1d?file=/src/components/SurveyPlayer.vue) to reproduce the error.

### Specify your

* browser: NA
* browser version: NA
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.56

**Comment by tsv2013** [comment]
Unfortunately the core reason of this issue is that survey-knockout-ui library re-initilises serializer in survey core with knockout-specific classes. Thus knockout-specific classes are created during de-serialization from survey JSON and break survey-vue-ui functionality.

We tried to solve this issue (Get rid of SurveyModel (core class) modifications in survey-knockout library #4754) earlier but I missed the above mentioned case. In the nearest half-year we plan to move to Vue3 and implement the "survey-creator-vue" library. That's why most likely we'll not fix this mixed platfoms issue.

Right now exactly for such a case we recommend as a workaround use the "survey-vue" library as a survey runner. Here is the updated codesandbox live example - https://codesandbox.io/s/surveyjs-creator-vue-forked-3y7l51?file=/src/components/SurveyPlayer.vue

Hope this help

**Comment by BrevAlessio** [comment]
Ok, thanks for the answer. We'll postpone the upgrade after the migration to Vue 3, which we are also planning for the next year.
