### ISSUE TITLE
Improve questions layouting

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#5178]
https://plnkr.co/edit/wu7Rw9kidBAzlSsB

As you can see, all input fields in the plunk above have different width, which doesn't look nice. It would be great if we added a capability to synchronize the width of input fields, either by default or using an option.

**Comment by mikeamelin** [comment]
- [ ] on start I expect actual width for columns
![Screenshot 2024-06-28 at 17 24 35](https://github.com/surveyjs/survey-library/assets/17025812/59ad6a66-8a88-4d3e-87b7-625f8d5dd40a)

- [ ] also actual values for questions
![Screenshot 2024-06-28 at 17 25 00](https://github.com/surveyjs/survey-library/assets/17025812/0672b971-d1e9-47c6-b759-3a9427bd1f98)

- [ ] ideally the columns should have min-width, not questions
![Screenshot 2024-06-28 at 17 29 23](https://github.com/surveyjs/survey-library/assets/17025812/78124e8b-4a05-493b-a232-742c0b28f76b)

- [ ] not expected behaviour 
![Screenshot 2024-06-28 at 17 30 33](https://github.com/surveyjs/survey-library/assets/17025812/fa137840-dd39-4bfb-9629-c948871e3dd8)
