### ISSUE TITLE
Values are not used in completedHtml regardless of the `useDisplayValuesInDynamicTexts` option

### ISSUE THREAD

**Issue by jmlopezo** [surveyjs/survey-library#5383]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
When using an expression to get the value of a radiogroup in the actions on completion it returns the text of the selected option instead of the value

### What is the expected behavior?
To return the value of the selected option

### How would you reproduce the current behavior (if this is a bug)?
Creator preview o library

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```json
{
 "logoPosition": "right",
 "completedHtml": "<h3>Thank you for your feedback {type}</h3>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "type",
     "useDisplayValuesInDynamicTexts": false,
     "choices": [
      {
       "value": "Value 1",
       "text": "Item 1"
      },
      {
       "value": "Value 2",
       "text": "Item 2"
      },
      {
       "value": "Value 3",
       "text": "Item 3"
      }
     ]
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
}
```

### Specify your

* browser: All
* editor version: 1.9.4

**Comment by jmlopezo** [comment]
Thanks @JaneSjs for replying, but I need a solution at the configuration level via the Creator, not by code.

**Comment by JaneSjs** [comment]
@jmlopezo, thank you for the clarification. We'll research this issue and reply shortly.
I transfered this issue to the survey-library repo because it actually relates to the library functionality. So please look forward to our reply.

To whom this might concern, it is possible to handle the [survey.onProcessHtml](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onProcessHtml) event and customize the HTML which appears on survey completion. For example, the following code displays a rating option value instead of text:
```
survey.onProcessHtml.add(function(sender, options){
  options.html = `<h3>Thank you for your feedback ${sender.getQuestionByName('type').value}</h3>`;
});
```
