### ISSUE TITLE
tagbox not allow to add new tag

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5689]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I was going to upgrade surveyjs in my app but I noticed that some important internals changed about dropdown. I was habit to use both select2 custom widgets but I cannot find any example among demos anymore. Are they still supported in recent surveyjs versions? 
Hence I wonder if it's better to upgrade surveyjs and switch to the improved native dropdown and tagbox question types.

for what concern the tagbox I noticed that the ability to add new tag is missing. Basically I hoped in something like [this](https://github.com/surveyjs/custom-widgets/issues/217)

Is there any chances to have it?

thanks a lot

**Comment by JaneSjs** [comment]
Hello @masciugo,
A Select2 demo was hidden from our website since we released enhanced [Dropdown](https://surveyjs.io/form-library/examples/create-dropdown-menu-in-javascript/reactjs) and [Tagbox](https://surveyjs.io/form-library/examples/how-to-create-multiselect-tag-box/reactjs) widgets. 
We actually recommend trying built-in questions instead of third-party ones.
Unfortunately, SurveyJS Dropdown/Tagbox don't enable users to add new dropdown entires/tags. Do I correctly understand that you're looking for the [Dynamic option creator](https://select2.org/tagging)? Please elaborate on your requirements to help me better frame them.

For now, you can proceed using the Select2 widget. An example is available at https://plnkr.co/edit/KlmWUejhTyZTC6bF.
For the record: we found an issue with using `renderAs` for custom widgets. We already fixed it (https://github.com/surveyjs/survey-library/issues/5654). The fix will be available with the next maintenance update.

I look forward to your reply.

**Comment by JaneSjs** [comment]
Hello @masciugo,
The Select2 demo works correctly with the latest update (v1.9.75): [Example](https://plnkr.co/edit/zX0JXRRHOozBhBCg).
You can enable the `allowAddNewTag` option to allow users add new tags to a Tag Box Select2 widget. 

Should you have any questions or require further assistance, please feel free to reactivate this thread.
