### ISSUE TITLE
Completion logic

### ISSUE THREAD

**Issue by GigiSan** [surveyjs/survey-library#5787]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

A survey is considered completed (and thus resetted, appreantly) after the last page. Only in this time the library has a set of functions to handle data saving. But I couldn't find a way to NOT consider a survey completed if an error occurred on save.

I could make use of the `onCompleting` and handle the logic there, but I would lose useful functions such as
```
options.showDataSaving()
options.showDataSavingSuccess()
options.showDataSavingError()
```
which are only available `onComplete` and, by the way, are shown for just a fraction of a second.
Plus, the saving could be async, which seems to break the functionality of `options.allowComplete` and `options.allow` in `onCompleting`.

Im my (very) humble opinion, a survey is not _completed_ if the results weren't used for their purpose. We may define it as _filled_ maybe, but resetting the whole survey just because the user reached the end seems a bit too much, especially if the survey is quite long.

Maybe I'm doing something wrong, but I think there should be native ways to allow a survey to complete only if the saving was successful and make use of the message functions _at that moment_. Only if the data was saved, then I can reset the survey.

Don't get me wrong, I don't want to overthrow the current logic, I just want to understand how does one handle data saving failure correctly under this logic.

### Specify your

* browser: Chrome
* browser version: 111
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.78

**UPDATE:**
I've been given some pointers on [#1242](https://github.com/surveyjs/survey-library/issues/1242) so I could workaround the issue. Would still be nice if we could invoke the toast messages whenever and would be possible to set a higher timeout for dismissal.

**Comment by CmdrBeavis** [comment]
Could not agree with this question more! I've been trying to figure out how to use `showDataSavingError()` for some time now, but since I can't find the TYPES for the objects, or in this case, the `options` argument to the onCompleted().add() function [to save my life], my linter / environment just keeps telling me that `'options' is of type 'unknown'` (which is SUPER frustrating!)

And for whatever it's worth, I've checked all the documentation I know how to and I can't find that `.add()` function documented _ANYWHERE_.

**Comment by andrewtelnov** [comment]
@CmdrBeavis All our events have functions: add/remove/clear.
The code will be:
```js
survey.onCompleted.add((sender, options) => {
 //Your code
});
```
I will suggest you to review our [examples](https://surveyjs.io/form-library/examples/).
You can choose the needed JavaScript framework on the top and then click on Code tab.
All our examples use onComplete event.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@CmdrBeavis Hm, for some reason CompleteEvent is not in d.ts. We need to expose them manually. 
Does [this code](https://codesandbox.io/s/surveyjs-angular-forked-3dmpqk?file=/src/app/components/survey.component.ts) work for you?

**Comment by andrewtelnov** [comment]
@dk981234 Should we add all event interfaces into entry.ts?

Thank you,
Andrew

**Comment by CmdrBeavis** [comment]
I'd certainly vote Heck Yes! I mean, eslint used as a TypeScript linter is
set up to be pretty strict, and having the types exposed seems like a
needed thing. That or at least make sure we know where to find the Types
[/type definition(s)] we might need so that we can expose them manually as
you said earlier.  : )

**Comment by CmdrBeavis** [comment]
Still working on it. Will get back to you in a bit.

**Comment by andrewtelnov** [comment]
@CmdrBeavis The following [PR](https://github.com/surveyjs/survey-library/pull/6406) created by @dk981234  adds missing interfaces into the d.ts file.
I have just merged it and the next version will have this fix. We will release it next week.

Thank you,
Andrew

**Comment by CmdrBeavis** [comment]
> @CmdrBeavis Hm, for some reason CompleteEvent is not in d.ts. We need to expose them manually. Does [this code](https://codesandbox.io/s/surveyjs-angular-forked-3dmpqk?file=/src/app/components/survey.component.ts) work for you?

It actually does seem to be working. (Still testing due to back-end issues.) What seems really weird to me is that even though `options` [in the argument list] is set as `any`, as soon as I type the period after `options` I actually do see a few `showData*()` options. 

Still had to put the `// eslint-disable-next-line @typescript-eslint/no-explicit-any` above the function declaration though.

```
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  public alertResults = (sender: Model, options: any) => {
  ...
```

**Comment by andrewtelnov** [comment]
@CmdrBeavis Please check with version 1.9.94 that we will release next week. You will be able to use CompleteEvent instead of any.
PS: We release weekly.

Thank you,
Andrew

**Comment by CmdrBeavis** [comment]
While I have gotten `options.showDataSavingError("My error text here.");` working, I have not seen / been able to find anything about controlling whether or not the "Try Again" button is shown.

**Comment by andrewtelnov** [comment]
@CmdrBeavis We don't have the ability to control the "Try Again" button. What do you want to do? We likely need additional API for your scenario.

Thank you,
Andrew

**Comment by CmdrBeavis** [comment]
> @CmdrBeavis We don't have the ability to control the "Try Again" button. What do you want to do? We likely need additional API for your scenario.
> 
> Thank you, Andrew

First, bummer, that's unfortunate. 

What I'd like to do is basically be able to hide it, and I'd base that on the returned status code [of the API call I'm making in order to save the completed questionnaire's data]. I mean, if we get say, a 500, trying again is totally pointless because there's a fair chance that it won't do any good. And in fact, if we get a bad request, trying again will for sure do nothing but frustrate the end user, let along the logging database! ; )

And in fact, if I could ask right here, should I make said API call in `onComplete()`, or `onCompleting()` ? Given some of the things I've read in this thread, and the other(s) we get lead to by this thread, it seems like `onCompleting()` is the right choice [in order to stop Completion as has been suggested above], that said, I'm fairly sure we'll want, if not NEED access to stuff like `options.showDataSavingError()` et al. 

Seems like a bit of a conundrum for sure.

Thanks for being so responsive Andrew!

**Comment by andrewtelnov** [comment]
@CmdrBeavis Do you want to add a paramter into `showDataSavingError` function to show/hide "Try Again" button?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@CmdrBeavis You can in fact remove the action by using the following code:
```survey.notifier.actionBar.actions = [];```.
Here is [the example](https://plnkr.co/edit/S6AR2qu9h9KzE3Hg).

Thank you,
Andrew
