### ISSUE TITLE
Drag-n-Drop Issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5836]
https://user-images.githubusercontent.com/17025812/226823392-46492872-6593-4805-8930-a136ccc31467.mov

**Comment by dmitrykurmanov** [comment]
The issus was appeared because of [this fix](https://github.com/surveyjs/survey-creator/issues/3747). And we sould reverse it.

After the investigation I've realized that we have one more problem with "dnd core from panel and page" here. We need to do the following:

1. Rollback [the fix ](https://github.com/surveyjs/survey-creator/issues/3747)
2. Add unit test with the following params:
 
![image](https://user-images.githubusercontent.com/22315929/228233789-257d16aa-6446-4043-9a16-92e53476a339.png)

3. Fix the test
