### ISSUE TITLE
Dual slider with NoUiSlider. Impossible to get the values on completed survey

### ISSUE THREAD

**Issue by geourjoa-tetras** [surveyjs/survey-library#5856]
Hello,

I'm trying to do a dual slider with survey js. I use Nouislider and Ia custom widget. I can display the dual slider but when I complete the survey, I can't get the value in result.

I have a sample of code https://codesandbox.io/s/surveyjs-dualslider-not-working-p738hg dislaying the problem.
I get only the value of slider and not the values of the dual slider.

Could you help me or say what I'm doing wrong ?

Thanks in advance

Geourjoa

### Specify your

* browser: Firefox Linux
* browser version: 110.0.1
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.9

**Comment by JaneSjs** [comment]
Hello @geourjoa-tetras,
A custom widget's value was not saved because there was no `question.valueChangedCallback` attached. 
You can follow the NoUlSlider implementation and attach this callback to update a widget's value once a question's value was changed: https://github.com/surveyjs/custom-widgets/blob/master/src/nouislider.js#L175. It is also required to unregister the value changed callback in the willUnmount function: https://github.com/surveyjs/custom-widgets/blob/master/src/nouislider.js#L190.

I updated your sample: https://codesandbox.io/s/surveyjs-dualslider-not-working-forked-0qfkyq?file=/index.html.
Now, survey results appear as follows:
```
result: {"dualslider":["21.00","33.00"],"slider":4}
```
Please feel free to reactivate this thread if you have any questions.
