### ISSUE TITLE
Check awnsered questions with panel collapsed

### ISSUE THREAD

**Issue by SekSion** [surveyjs/survey-library#5889]
Hi, im trying to check how manny questions i have under a collapsed panel but the DOM content is not loaded the first time the panel is created, so i have to expand it one time so i can check how manny questions i have awnsered, doing something similar to "2 out of 5 questions awnsered"

Is there a way to make the content hidden but available at the dom level?

* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.21

**Comment by JaneSjs** [comment]
Hello @SekSion,
If you wish to check how many questions inside a panel were answered, you can get a target panel from a survey panels collection ([survey.getAllPanels](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getAllPanels)), get a panel's [question](https://surveyjs.io/form-library/documentation/api-reference/panel-model#questions) collection, and check whether or not a question has value using the [question.isEmpty](https://surveyjs.io/form-library/documentation/api-reference/question#isEmpty) property.

Please let me know if this helps. Otherwise, I'll assist you further.

**Comment by SekSion** [comment]
Thank you for replying, that would make sense the issue is that inside the panel contain some Custom React Components where the only way we were able to create them was like this
![image](https://user-images.githubusercontent.com/46030872/228578232-f9092289-6d9d-412b-973c-537355723441.png)
![image](https://user-images.githubusercontent.com/46030872/228578298-65c69bf8-0486-4106-80b4-798b09a58d4d.png)
![image](https://user-images.githubusercontent.com/46030872/228578465-171f610b-5812-4897-a365-aa2b1195c215.png)

The main problem is that we need the grid to render first in order to understand if it has what it needs to be "completed" but since the panel is collapsed it does not render the grid and gets the required data, so there should be a way to make the panel collapsed and render the content inside by option no?

**Comment by JaneSjs** [comment]
Hello @SekSion,
The `isRequired` option is what basically allows you to prevent users from leaving questions unanswered.

Am I right that you wish to check whether or not a user can complete the survey/page depending on a custom survey question?
Could you please share a demo?
