### ISSUE TITLE
Can we have Previous button after completing the survey for testing purpose

### ISSUE THREAD

**Issue by syash2015** [surveyjs/survey-library#607]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I know it's not a good question but can we have the previous button after completing the survey.

### What is the expected behavior?
Can we have previous button  after completing the survey.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@syash2015, hello! If I uderstand you correctly, you want to review the survey after complete. What about the repeat completion of the survey? Should this be possible? Or you just want possibility to review survey in "display" mode? Could you please describe you use case?

**Comment by syash2015** [comment]
Mine is large set of questions and after completing the survey I would display results based on the answers given. if I have answered 20 questions and for 21st question I select option 1 which  will complete the survey. If I would have selected option 2 it will continue to question # 22. So if I want to change the answer from option 1 to option 2 I have to again answer 20 questions.

**Comment by andrewtelnov** [comment]
@syash2015 I understand what you are talking about. I had completed such type of surveys, so the end-user may preview answers by sections and comeback and edit one particular section.
It is doable with the current version, but it requires to write a lot of code.
We will keep this scenario in mind. Unfortunately, we do not have recourse to work on this feature or example right now, since there are already many urgent tasks we have for the next several iterations.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@syash2015 We can show preview before complete now. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-showpreview).

Thank you,
Andrew
