### ISSUE TITLE
survey-angular-ui - Integrate Third-Party Angular Components Not works on optimized build

### ISSUE THREAD

**Issue by morettolss** [surveyjs/survey-library#6113]
639 / 5.000
Risultati della traduzione
Risultato di traduzione
I'm integrating a 3rd party component on survey-angular-ui (https://www.npmjs.com/package/survey-angular-ui)
Everything works fine until I do the build.
The build happens without any errors, but when I try to view the survey it doesn't return my custom field.

The problem is replicated by simply doing the build of:
https://github.com/surveyjs/code-examples/tree/main/integrate-third-party-angular-components

In particular I noticed that the dev build seems to work, the production build doesn't (so change "optimized" to true/false).
There is no js or angular error

The problem is mainly on the frontend and not on the creator

**Comment by andrewtelnov** [comment]
@morettolss Angular removes your code because it doesn't find any reference on this question. Angular could not understand that your code will be executed after parsing your survey JSON.
You can add this line into your AppModule or AppComponent:
`static declaration = [YourQuestionClassName];`

@RomanTsukanov Could we add this into our documentation? @dk981234 could provide you more information regarding this Angular related issue.

Thank you,
Andrew

**Comment by morettolss** [comment]
HI,
thanks for the quick response.
I confirm that by adding
`static declaration = [YourQuestionClassName];`
to app.component.ts, just before the constructor
it works properly
