### ISSUE TITLE
Survey viewer fails to render if the survey editor has been opened during the same session

### ISSUE THREAD

**Issue by KsyDar** [surveyjs/survey-library#6401]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?

I have the same problem as #1698 

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.9.93

**Comment by andrewtelnov** [comment]
@KsyDar Could you please provide an example to see the issue?

Thank you,
Andrew

**Comment by KsyDar** [comment]
https://watch.screencastify.com/v/G6kR3arkLen7k3HTF5vO

**Comment by andrewtelnov** [comment]
@KsyDar Unfortunately, there is no way we can't help you by seeing this video.
At first, it is your application and we have no idea how you have implemented your back-end part.
If you provide us with non-working application in plunker or CodeSandbox then we can take a look and find the reason of the issue.
Right now, I strongly believe that your issue is somewhere in your back-end code. Of course, I can be wrong, but there are hundrends applications around that have the similar functionality and use our libraries and they work correctly.

Thank you,
Andrew
