### ISSUE TITLE
Validation on custom component not working

### ISSUE THREAD

**Issue by nehemiah-tzur** [surveyjs/survey-library#6596]
### Are you requesting a feature, reporting a bug or ask a question?
Bug/Question/Request

### What is the current behavior?
I am trying to add a validator for my custom component, but it never triggers properly. I've added validators to try and validate the file type is the correct one. The issue with the acceptedTypes is that it won't prevent the user from uploading an incorrect type. 

### What is the expected behavior?
It would be nice if there was an easy way to have acceptedTypes enforce that the type uploaded is that type and do an automatic validation. Currently I used the validators array, but the expression does not seem to work. 

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/dc8VB0LqREUUpOpq

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/dc8VB0LqREUUpOpq

### Specify your

* browser: chrome
* editor version:

**Comment by JaneSjs** [comment]
Hello @nehemiah-tzur,
Please accept my apologies for the delayed reply.

The [acceptedTypes](https://surveyjs.io/form-library/documentation/api-reference/file-model#acceptedTypes) property of a File question allows developers to set allowed types of uploaded files. 

This option specifies the [accept](https://www.w3schools.com/tags/att_input_accept.asp) attribute value for the underlying `<input>` element. This setting filters a list of file types in the upload file dialog. However, the `acceptedTypes` property doesn't actually prevent users from uploading other file types because a user may select All Files in the upload file dialog.

If you wish to restrict a user from uploading specific file types, you can handle the [survey.onUploadFiles](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onUploadFiles) function and programmatically cancel file upload.

I hope this information helps. Please let me know if you have any questions.
