### ISSUE TITLE
Possibility to disable/replace automatic key-value pairing done by survey when registering a custom tagbox component

### ISSUE THREAD

**Issue by taylordardono** [surveyjs/survey-library#6603]
### Are you requesting a feature, reporting a bug or asking a question?

Request

### What is the current behavior?

 Tagbox question types automatically generates a map with choices key-value pairs even if the user register a custom component for the tagbox type. This is an issue when the computation time goes way up for thousands of choices(e.g. taking in account that there is no option to use lazy-load) which can block the correct use of the UI.

### What is the expected behavior?

If the user register a custom component to handle the tagbox type, automatically disable the key-value map of choices done by survey, or at least give the posibility to replace/disable that computation so the developer can do it him/herself.

### How would you reproduce the current behavior (if this is a bug)?

Loading a huge list of choices(like 40000 items), on selecting a choice for the first time or given a default selection included in the choices list on load -where survey creates automatically the key-value map to handle the display information of tags faster in the next selections I assume- it can take up to 13 seconds to resolve that computation.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

### Specify your

* browser: Chrome
* browser version: 115.0.5790.110
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.9.98

**Comment by JaneSjs** [comment]
Hello @taylordardono,
SurveyJS Tag Box question supports lazy loading for its choices: [View Demo](https://codesandbox.io/s/suspicious-bouman-yp34kw?file=/src/json.js).

![image](https://github.com/surveyjs/survey-library/assets/22372972/12d939b1-5b18-4ade-9a4e-449d801e1564)

For more information on how to enable lazy loading, please refer to the following demo: [Lazy Loading](https://surveyjs.io/form-library/examples/lazy-loading-dropdown/).

Should you have any questions or require further assistance, please feel free to reactivate this thread.

**Comment by unai-reliefapp** [comment]
Hi @JaneSjs , thanks for the response and also sorry for the late reply.
I checked the lazy load option, but unfortunately the url I have to work with does not have in their side the possibility to use any kind of filtering or pagination, therefor your current solution does not suit our needs.

So we have to load the whole chunk at once. In order to fully handle the tagbox feature we register a custom tagbox component for that question type, but still surveyjs is triggering some callbacks that may be useful for the default tagbox of survey, but that we want to avoid on a custom registered tagbox component, as it's slowing the UI interaction between 10-13 secs.

So we were asking to somehow give the possibility to disable all related callbacks or computations for the default surveyjs tagbox component if developer register a custom one, so we can have full control of how all related features(placeholders, change events, list behaviors, key-value mapping etc.) to the tagbox -or any other component- are handled.

Anyway we manage to implement a quick fix overwriting explicitly some methods in the class prototype, so is not really urgent.

Thanks for your time

**Comment by JaneSjs** [comment]
Hello @taylordardono,
If you wish to implement a custom question, refer to the documentation articles below for a step-by-step tutorial. 

* [Integrate Third-Party React Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)
* [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)

**Comment by taylordardono** [comment]
I could not find that, it would be very helpful

Thanks again for time @JaneSjs
