### ISSUE TITLE
Changing display mode of form breaks progress bar navigation

### ISSUE THREAD

**Issue by emailtosamit** [surveyjs/survey-library#6653]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?
Following is my scenario:-
* Form designed with three pages with progress bar for navigating to different pages.
* At Initial load showing form in read only mode by setting mode property to display. **Noticed the page navigation is working fine.**
* When user click on edit button(custom) the form mode is change to edit mode by setting mode property to edit. The form is now changed to edit mode and user can enter data.
* Noticed when the mode of form changed to edit mode then: -
         1)  The user automatically navigated back to first page. for e.g. if you are on page 3 and click edit button then you get redirected to page1.
         2)  The page navigation does not work anymore. for e.g. now if click page 2, page 3 then you do not redirect to that corresponding page.

### What is the expected behaviour?
When edit button is pressed which changed the mode of form to edit mode then:-
1) the user should stay on the same page instead of redirected to first page. for e.g if you are on page 3 and clicked on edit button then you should be staying at page 3 instead of redirected to page 1.
2)The page navigation should be functional after chaning mode. for e.g if you click on page 1 or page 2 or page 3 in progress bar then you should be redirected to corresponding page.

### How would you reproduce the current behavior (if this is a bug)?
i have created a small react app to reproduce the issue.

#### Provide the test code and the tested page URL (if applicable)

Following is JSON of form:-
const surveyJson = {
    "logoPosition": "right",
    "pages": [
     {
      "name": "Personal Infomrmation",
      "elements": [
       {
        "type": "panel",
        "name": "panel1",
        "elements": [
         {
          "type": "text",
          "name": "firstName",
          "title": "Enter Name"
         }
        ]
       }
      ],
      "title": "Personal Information"
     },
     {
      "name": "Address",
      "elements": [
       {
        "type": "text",
        "name": "address",
        "title": "Enter Address"
       }
      ],
      "title": "Address"
     },
     {
      "name": "Nationality",
      "elements": [
       {
        "type": "text",
        "name": "nationality",
        "title": "Current Nationality"
       }
      ],
      "title": "Nationality"
     }
    ],
    "showProgressBar": "top",
    "progressBarType": "buttons"
   };

Following is the react component code
class App extends Component {
  constructor() {
    super();
    this.state = {mode: "display"};
  }
  render() {
    const surveyModel = new Model(surveyJson);
    surveyModel.mode =this.state.mode
    return (<div>  
                     
              <button onClick={() => this.changeDisplayMode("Edit")}>Edit</button>
              <Survey model={surveyModel} />
            </div>);
    
  }
  changeDisplayMode = (strMode) => {   
    this.setState({ mode: strMode });
  }
}

```




```

### Specify your

* browser: Edge
* browser version:
* surveyjs platform react
* surveyjs version: "survey-react-ui": "^1.9.101",

**Comment by JaneSjs** [comment]
Hello @emailtosamit,
Thank you for the detailed explanation and the sample.

Currently, the `surveyModel` instance is created within the `render` method on each render cycle. This means that every time the component re-renders, a new `surveyModel` instance is created, and its `mode` property is set based on the current state.
However, this approach has a problem. When you update the state using `this.setState({ mode: strMode })`, the `surveyModel` instance does not automatically get updated to reflect the new mode because you're creating a new instance of the model on each render. 

Please update the code as follows:
```js
import React, { Component } from "react";
import { Model } from "survey-core";
import { Survey } from "survey-react-ui";
import "survey-core/defaultV2.min.css";
import "./index.css";
import { json } from "./json";

class SurveyComponent extends Component {
  constructor() {
    super();
    this.state = { mode: "display" };
    this.surveyModel = new Model(json);
    this.surveyModel.mode = this.state.mode;
  }
  changeDisplayMode = (strMode) => {
    this.setState({ mode: strMode });
    this.surveyModel.mode = strMode;
  };

  render() {
    return (
      <div>
        <h2>current mode is {this.state.mode} !</h2>
        <button onClick={() => this.changeDisplayMode("Edit")}>Edit</button>
        <Survey model={this.surveyModel} />
      </div>
    );
  }
}

export default SurveyComponent;
```
[View Demo](https://codesandbox.io/s/broken-fog-sgwqqz?file=/src/SurveyComponent.jsx:215-803)

In the updated code, the `surveyModel` instance is created within the `constructor` of the component. This means that the instance is created only once, when the component is initialized. The `mode` property of the `surveyModel` instance is set based on the initial state.

Since the `surveyModel` instance is created only once and stored as a property of the component (`this.surveyModel`), updates to the `mode` property are directly reflected in the instance, and the reactivity works as expected.
By ensuring that the `surveyModel` instance is not recreated on every render cycle, the updated code maintains a consistent reference to the survey model, making the reactivity with the component's state effective.

Now, when a user enables the edit mode, a survey remains on the currently selected page, and navigation works correctly.
![Clipboard-File-1.png](https://surveyjs.answerdesk.io/internal/attachment/file/cb32d65c-8cd5-413c-895e-3b69cef8a4c7)
I hope this helps. Please let me know if you have any questions or require further assistance.

**Comment by emailtosamit** [comment]
Thanks for your prompt response and detailed explanation. Appreciate it.
