### ISSUE TITLE
TOC - Enhancement idea

### ISSUE THREAD

**Issue by tstrumfels** [surveyjs/survey-library#6926]
Regarding navigation, the new TOC is great for navigating page to page, but was looking to get more granular.

Within a page, we can have multiple panels, which would definitely be useful if exposed as child items under each page in the TOC.

Incorporated my own, using the data model.  Also includes a simple indicator to show user if a page/subsection is complete or not

![image](https://github.com/surveyjs/survey-library/assets/5797464/4c53f7a3-1cbf-43a4-b48d-87fc5270fc79)

**Comment by JaneSjs** [comment]
Hello @tstrumfels,
Please accept my apologies for the delayed reply. 

Unfortunately, we don't currently consider extending our TOC.


In the meantime, you can implement a custom TOC which would include survey panels and display the information about the progress per pages/number of questions answered per page.

To implement a custom table of contents, register a custom component and add it as a layout item to the `left` container.

An example of how to implement a custom layout item is available at [Percentage Progress Bar](https://surveyjs.io/form-library/examples/progress-bar-with-percentage/angular). 

A template for a built-in TOC Angular component (ProgressTocComponent) is available in our source code: [progress.component.ts](https://github.com/surveyjs/survey-library/blob/64054532432777a2aa339d693b6866d1b62f3512/packages/survey-angular-ui/src/components/progress/toc/progress.component.ts). If you use another JavaScript platform, please feel free to locale a template for your JS platform. Let me know if you have difficulties with that.

For the record: you can also review the following ticket where I shared a React Demo of a custom TOC: [TOC Customization](https://surveyjs.answerdesk.io/internal/ticket/details/T14101).

I hope this information may help. Should you have any further questions, please feel free to reactivate this thread.

Thanks

**Comment by JaneSjs** [comment]
Hello @tstrumfels,
Please be informed that with v1.11.14 and newer, a Table Of Contents supports a custom item template.

The following demo shows how to implement a custom TOC item and:
* Display information about the answered and total questions per page.
* Highlight a TOC item with Red/Yellow/Green depending on the number of answered questions.
![image](https://github.com/user-attachments/assets/d31ddb0f-e565-47cf-943e-f75a4c764e35)

Follow these steps:

1. Implement a component that renders item markup.
The component accepts the item configuration object as a prop. You can use its item property to access the IAction which corresponds to the current page item within a TOC. Use this object to retrieve information about the current page and its answered and total question count.

2. Register the component so that it can be accessed by name.

In React and other JS applications, register the component in ReactElementFactory as shown in the CustomTocItem.jsx file. In Angular, register the component in AngularComponentFactory as shown in the toc-custom-item.component.ts file. In Vue, implement the CustomTocItem component as shown in the CustomTocItem.vue file and register it within application components.

3. Obtain the Table of Contents navigation element and set the itemComponent property to the custom component name.
```
survey.findLayoutElement("toc-navigation").data.listModel.itemComponent = "sv-custom-toc-item";
```
* [View Demo for JS](https://codesandbox.io/p/sandbox/z4nvh5)
* [View Demo for React](https://codesandbox.io/p/sandbox/pf3qx7)
* [View Demo for Angular](https://codesandbox.io/p/sandbox/fjgly6)
* [View Demo for Vue](https://codesandbox.io/p/sandbox/qwvgcl)
