### ISSUE TITLE
Result of expression question is stringified

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#7050]
### Are you requesting a feature, reporting a bug or asking a question?
Bug
This behavior is introduced by the version 1.9.108

### What is the current behavior?
the result of an expression which is a complex type is stringified.

### What is the expected behavior?
the result of an expression if it is a complex type should not be stringified

### How would you reproduce the current behavior (if this is a bug)?
sandbox : https://codesandbox.io/s/fervent-feynman-syklql 
you can see in the log data when you change the text question value that the value of the question testExpression is a stringified array instead of

### Specify your

* browser: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.108

**Comment by JaneSjs** [comment]
Hello @FHourmy,
Thank you for sharing a demo. I tested your sample and confirmed that this behavior exists in an older version of a SurveyJS Form Library (for instance, 1.9.90). Would you please elaborate on the expected behavior? 
For now, you can programmatically convert an array of values into a required representation.

Consider the updated demo: https://codesandbox.io/s/focused-poincare-w6p6zt?file=/index.js:43-218.
```
Survey.FunctionFactory.Instance.register("testExpression", () => {
  const values = [{ value: "t1" }, { value: "t2" }];
  const res = JSON.stringify(values);
  return res;
});
```
Thanks

**Comment by FHourmy** [comment]
Hello @JaneSjs 
The problem is the type of stored value.

### in version 1.9.108 the **current behavior**
The returned value is stored as a string [object,object
![image](https://github.com/surveyjs/survey-library/assets/34136072/57f861f7-39d1-47ba-b45e-6c7c8314be4b)
repro on https://codesandbox.io/s/fervent-feynman-syklql?file=/index.js


### in older version the **expected behavior** (for instance 1.9.90)
The returned value is stored in the same way it is returned, conserving its type
![image](https://github.com/surveyjs/survey-library/assets/34136072/d15b84d6-0a4d-495a-ba01-4a63c87e2417)
repro on https://codesandbox.io/s/festive-lewin-kv82v3?file=/index.html


### In your edit
You stringify the array to store it, losing its type and potential complex properties (can't store functions this way for exemple)
![image](https://github.com/surveyjs/survey-library/assets/34136072/0e2b44ca-5890-4aec-9e65-d458264d0ba3)
repro on https://codesandbox.io/s/focused-poincare-w6p6zt?file=/index.js

Thank you for your time :)

**Comment by andrewtelnov** [comment]
@FHourmy The issue was introduced by fixing [this issue](https://github.com/surveyjs/survey-library/issues/6886).
I have changed the fix. In fact, it was fixed incorrectly. I should not change the expression question model code.
I wrote the correct unit tests for that fix and added unit test for your case in the PR above.

Thank you,
Andrew
