### ISSUE TITLE
goNextPageAutomatic has a delay

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#7226]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Since version 1.9.113 When the option goNextPageAutomatic is set to true, once all the answers are given, there is a delay before changing page

### What is the expected behavior?
When the option goNextPageAutomatic is set to true, once all the answers are given, there is no delay before changing page

#### Provide the test code and the tested page URL (if applicable)

repro (bug) 1.9.113 : https://codesandbox.io/s/recursing-bhaskara-mgfl5y => fill the text, click outside, you can see a delay before page change

repro (no bug) 1.9.112 : https://codesandbox.io/s/clever-dream-xpdjlr => fill the text, click outside, you cannot see any delay before page change

### Specify your

* browser: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.113

**Comment by JaneSjs** [comment]
Hello @FHourmy,
v1.9.113 introduces a special auto-delay feature for the `goNextPageAutomatic` mode (see [this Release Note](https://surveyjs.io/stay-updated/release-notes/v1.9.113)). We've been reported that the previous behavior (immediately switching to another page) introduced some confusion because a user was unable to actually see the selected. To handle this issue, we introduced a 300-millisecond delay before switching to the next page. If you want to disable this delay value, set the [settings.autoAdvanceDelay](https://surveyjs.io/form-library/documentation/api-reference/settings#autoAdvanceDelay) property to 0:
```
import { settings } from "survey-core";

settings.autoAdvanceDelay = 0;
```
Please feel free to reactivate this thread if you have any further questions.
