### ISSUE TITLE
Multi-Page Survey with Timer - No required validation occurs when the timer lapses

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7742]
User Issue: T16546 - Timer/quiz question
https://surveyjs.answerdesk.io/internal/ticket/details/T16546
*** 
To reproduce the issue, run [this demo](https://plnkr.co/edit/LfouAMm2Vtpv1JyW). Answer question 1 and question 2; when the time elapses, a survey is completed regardless of a required question on page 3.
![image](https://github.com/surveyjs/survey-library/assets/22372972/cacaf209-50cd-4637-a7cf-e09e1f44ef19)

Expected behavior: a validation error appears preventing a survey from being completed; a timer stops at 0.

**Comment by andrewtelnov** [comment]
I believe it is a correct behavior. Otherwise, what is the point of having timer if the survey could not be finished in this time?
If you wish to have a required questions, then please move them into the started page. The timer will be started when a user click on "Start" button on the start page. Your user will have time to fill all required questions on the started page before the timer is started.
Please set [survey.firstPageIsStarted](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#firstPageIsStarted) property to true to make the first page started.

Thank you,
Andrew
