### ISSUE TITLE
How to: register custom SVG icons from a folder

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7800]
Please update the [UI Icons](https://surveyjs.io/form-library/documentation/icons) help topic and add an example on how to register a bunch of custom icons in a SurveyJS Form Library.

T16625 - SvgRegistry not working as expected
https://surveyjs.answerdesk.io/internal/ticket/details/T16625)

**Comment by novikov82** [comment]
spike - https://github.com/surveyjs/survey-creator/compare/issue/5185-Survey-Description-Property-Editor-allows-entering-new-lines-which-are-further-eliminated-in-preview?expand=1

**Comment by novikov82** [comment]
We are making a web application, there are no folders, no file system. In our project, we use webpack, and the registerFromFolder function was needed only for us, because it is tailored for webpack.
When file icons appear in a user project, we no longer influence them. How the project is assembled, what happens to the files - we do not know and should not know. For users, we only describe the use of the registerIconFromSvg function - registering one single svg icon contained in a line. The user must take care of how he will receive the contents of his files and how he will pass them to the registerIconFromSvg function.
