### ISSUE TITLE
RegEx Validation doesn't display a validation error based on the specified regular expression

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8076]
T17595 - Integer validators not always being used
https://surveyjs.answerdesk.io/internal/ticket/details/T17595
***
The following regex: `^\d+$` allows only integers.
It works when you check the value in JavaScript: [View Demo](https://plnkr.co/edit/LpsQAFUsbqwaBMtf).

However, if you setup SurveyJS RegEx validation and enter `e`, no validation error occurs.

**Comment by andrewtelnov** [comment]
@JaneSjs Here is [the updated example](https://plnkr.co/edit/PCxg14TJf5e1sCIn?preview).
We don't need validator for numeric type, since the question returns numeric. "e" or "3e" will return undefined. "2e2" will return 200.
The '\\d+' works for input type text. It should be "\\d" not "\d".

Thank you,
Andrew
