### ISSUE TITLE
Panel Dynamic - allow add panel description above add panel text button?

### ISSUE THREAD

**Issue by y0n4** [surveyjs/survey-library#8379]
### Are you requesting a feature, reporting a bug or ask a question?
Question (possibly a feature)
Is it possible to have a "add panel" description right above the add panel button? Our panel dynamic has numerous elements, and can get very long with other nested panel dynamics, so we want to explain to our users what the button will do when they reach towards the end of the panel dynamic. That way we can address the fundamental usability of the button with a line of instructional text.

### What is the current behavior?
The closest thing we can get is using `descriptionTitle = "underInput"` 
<img width="777" alt="Screenshot 2024-06-05 at 4 18 36 PM" src="https://github.com/surveyjs/survey-creator/assets/25360903/420018c1-3943-44ff-959f-24bb9b94f493">

### What is the expected behavior?
Ideally we want to have a description text where the purple arrow is pointing to. And we can still keep the descriptionTitle to be under title
<img width="777" alt="Screenshot 2024-06-05 at 4 21 57 PM" src="https://github.com/surveyjs/survey-creator/assets/25360903/e4a1174c-290b-45ec-a8ef-98b2c8416cb5">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/y0n4/pen/ExzXNMZ?editors=0010

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 125.0.6422.11
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.10.3

**Comment by JaneSjs** [comment]
Hello,
You can show a description under the panel by using the [`QuestionPanelDynamicModel.descriptionLocation](https://surveyjs.io/form-library/documentation/api-reference/dynamic-panel-model#descriptionLocation) property.
```
"descriptionLocation": "underInput"
```
However, you may wish to additionally apply the following CSS to add an indent between the description and the bottom border.
```cs
.sd-description.sd-question__description--under-input {
    padding-bottom: calc(var(--sd-base-vertical-padding));
}
```
[View Demo](https://codepen.io/JaneGaid/pen/qBGjQEP)
![image](https://github.com/surveyjs/survey-library/assets/22372972/6c2bfb59-10ff-433c-bc07-9711f88b6845)

Please let me know if this option works for you.

**Comment by y0n4** [comment]
Hi, thanks for the response. Sorry- my question was if it's possible to have an add panel text description above the add panel text button (in this case "add vacation" button) like this image, and if not could it be considered to be put in as a feature request?
![image](https://github.com/surveyjs/survey-library/assets/25360903/bf2ffcfd-1b2a-44bd-bef3-4e9cb8705c79)

The answer you provided, `"descriptionLocation": "underInput"` is the closest thing we can do but it's not exactly what we are looking for.

**Comment by JaneSjs** [comment]
Hello @y0n4,
Unfortunately, there is no option to render an additional description attached to the Add Panel button. To go simple, please consider adding some descriptive text to the "Add Panel" button's [`title`](https://surveyjs.io/form-library/documentation/api-reference/iaction#title).
If you want to add more text, consider implementing a custom [IAction](https://surveyjs.io/form-library/documentation/api-reference/iaction) and render it using a custom component instead of a default Add Panel button component. To add a custom action, implement the [`survey.onGetPanelFooterActions`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onGetPanelFooterActions) function. To override the default button component, define the [`IAction.component`](https://surveyjs.io/form-library/documentation/api-reference/iaction#component) property.

Please drop me a line if you have further questions.
