### ISSUE TITLE
The timer is suspended and displays the wrong time if another browser tab was opened during the quiz

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8509]
T18850 - Quiz with Timer Issue
https://surveyjs.answerdesk.io/internal/ticket/details/T18850
***
To reproduce the issue, run [this demo](https://plnkr.co/edit/0E451YRIfGkcynIg). The timer is started automatically.
![image](https://github.com/surveyjs/survey-library/assets/22372972/df6c10a0-4249-4250-b773-2929a78e0234)

Open another browser tab and wait for 2 minutes. Return to the quiz page and notice that the time has not elapsed.
![image](https://github.com/surveyjs/survey-library/assets/22372972/12c6be1e-de8f-45dd-af46-5e7cb050f5b4)

Instead, the timer continues with 1 minute.

![image](https://github.com/surveyjs/survey-library/assets/22372972/6a3a3d45-14a8-488c-88f1-6c302f8a888b)

https://github.com/surveyjs/survey-library/assets/22372972/e3d5447d-fac1-4b9f-907f-32edd4f64801

**Comment by tsv2013** [comment]
This is the shrome (probably and other browsers) designed behavior. See the https://developer.chrome.com/blog/background_tabs?hl=en article.

**Comment by tsv2013** [comment]
Some workarounds are discussed on SO - https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs - but I boubt they're reliable enough.

**Comment by andrewtelnov** [comment]
The feature to check how many seconds are left before the timer fires again has been added. If the timer exceeds the maxTimeToFinish for a page, the survey will navigate to another page. The suspended time will be the difference between the time spent on this page prior to reaching maxTimeToFinish.

For example, if a page has a maxTimeToFinish of 20 seconds and a user spends 5 seconds on the page before switching to another tab for a minute before returning, the survey will move to another page. The timer on the new page will restart from 0, and the survey time will increase by 15 seconds instead of the 60 seconds initially spent (20 - 5 = 15).
