### ISSUE TITLE
Matric column header

### ISSUE THREAD

**Issue by rsantini62** [surveyjs/survey-library#8881]
I would like to have my column headers be static. I am using a surveyjs maxtix question. So that they are always on top when you scroll up and down the page.  Here is a link to my example.

https://plnkr.co/edit/2PBf3TtpARSmCst2

Thank you

**Comment by JaneSjs** [comment]
Hello,
Unfortunately, it is not possible to fix the matrix heading area. While you can fix a survey/form header using custom CSS ([View Demo](https://codesandbox.io/p/sandbox/old-silence-qwkxd9)), the matrix header cannot be fixed since the matrix spans the entire form area and lacks a fixed width.

If you have a large matrix and want to ensure the column headers remain visible, consider splitting the matrix into multiple smaller matrices. Each one will fit within the screen area, preventing the column headers from being hidden.

If you have any further questions, please let us know.

Thanks!

**Comment by rsantini62** [comment]
Thank you Jane!
________________________________
