### ISSUE TITLE
Signature Pad - Impossible to upload an image by URL - Access to image at X from origin Y has been blocked by CORS policy

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8936]
T20294 - CORS policy error, but only in signaturepad (bug?)
https://surveyjs.answerdesk.io/internal/ticket/details/T20294

**Comment by tsv2013** [comment]
Because of CORS settings we can load image, but we're not able to get image content - e.g. base64 encoded bytes to add into survey result.
See the https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image for more details:

> If the foreign content comes from an image obtained from either as [HTMLCanvasElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement) or [ImageBitMap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap), and the image source doesn't meet the same origin rules, attempts to read the canvas's contents are blocked.
> 
> Calling any of the following on a tainted canvas will result in an error:
> 
> Calling [getImageData()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) on the canvas's context
> Calling [toBlob()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob), [toDataURL()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) or [captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) on the [<canvas>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas) element itself
> Attempting any of these when the canvas is tainted will cause a SecurityError to be thrown. This protects users from having private data exposed by using images to pull information from remote websites without permission.

Thus we can even show such an image in canvas, but willn't be able to get it content or modify it. If it will be enough (in read only mode), we could implement it, but I doubt it will be actually useful - it will cause an unexpected behavior and further questions and/or issues.
