### ISSUE TITLE
Custom attribute change language

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#9009]
Hello, I use the latest survey library, and the custom attributes don't change properly when changing the language. Custom property "info", which is visible when hovering over the title. What's going on?
Looking forward to hearing from you.

Example address：https://codesandbox.io/p/sandbox/surveyjs-angular-forked-w79l77

**Comment by JaneSjs** [comment]
Hello @fengzhihenxs,
The `options.question.info` returns the current localization text. The issue is that when a user changes the locale, the tooltip text is not updated. Instead, it uses the default locale text which you defined initially. 
In SurveyJS Forms, we do not basically use tooltips because they are unavailable on mobile devices. 
I may recommend that you consider an alternative option. Use [`question.description`](https://surveyjs.io/form-library/documentation/api-reference/question#description) to display some helpful text; register a custom [title action](https://surveyjs.io/form-library/examples/modify-titles-of-survey-elements/) to allow users to show and hide the descriptive text: [View Demo](https://codesandbox.io/p/sandbox/surveyjs-angular-forked-q893mz?file=%2Fsrc%2Fapp%2Fcomponents%2Fjson.ts%3A1%2C21&workspaceId=c1318f77-19a4-463d-b58a-86fcfde8c6c4).
![image](https://github.com/user-attachments/assets/c01a0707-83fe-4ea4-b801-175ba851ff41)

Let me know if this option suits you.

**Comment by fengzhihenxs** [comment]
Thank you so much. This is also an option that there is no way out.
